### ISSUE TITLE
How to replace Symbol::section_kind

### ISSUE THREAD

**Issue by RazrFalcon** [gimli-rs/object#108]
`Symbol::section_kind` was removed, but without the transition notes. How to convert this code to a newer version?

```rust
if symbol.section_kind() != Some(object::SectionKind::Text) {
    continue;
}
```

**Comment by philipc** [comment]
The closest behaviour will be to look up the corresponding section using `Symbol::section_index`, and then use `ObjectSection::kind`. Otherwise maybe `Symbol::kind` will be good enough. If you can point me to where you are using it then I might be able to suggest which is better.

**Comment by RazrFalcon** [comment]
I'm using it to collect "function names":
https://github.com/RazrFalcon/cargo-bloat/blob/353d8a34dd9bbc8ddd3a1b7dd0a9716fb12e77c8/src/main.rs#L544

Maybe I don't need it at all. Not sure.

**Comment by philipc** [comment]
I think this should work:
```rust
if symbol.is_undefined() || symbol.kind != object::SymbolKind::Text {
            continue;
}

**Comment by philipc** [comment]
Also, beware that not all file formats have symbol sizes (which you are using at https://github.com/RazrFalcon/cargo-bloat/blob/353d8a34dd9bbc8ddd3a1b7dd0a9716fb12e77c8/src/main.rs#L555)

**Comment by philipc** [comment]
Oh, wait on, this is using `symbol_map` for the sizes, that should be ok!

**Comment by RazrFalcon** [comment]
Thanks!
