### ISSUE TITLE
[write machO] Text section assumed to be pure instructions

### ISSUE THREAD

**Issue by bjorn3** [gimli-rs/object#137]
https://github.com/gimli-rs/object/blob/24ba5e1304d2236bf64c6745e36b509e4b045d91/src/write/macho.rs#L245

This is incorrect for Cranelift, which puts jump tables right next to the function code.

This is the same as https://github.com/m4b/faerie/issues/101.

**Comment by philipc** [comment]
Do you think we need to make this configurable? Would it matter if we always made it `S_ATTR_SOME_INSTRUCTIONS` only?

**Comment by bjorn3** [comment]
I dont know.

**Comment by philipc** [comment]
Did the `S_ATTR_PURE_INSTRUCTIONS` cause a problem for cg_clif? Did you check that removing it fixes the problem (or that it still works after removing it if there wasn't a problem)?

From a brief look, lld always outputs `S_ATTR_PURE_INSTRUCTIONS` for `__TEXT,__text`, regardless of what the input object files specified.

I just don't know enough about this to know what the correct fix is, or if it even matters.

**Comment by bjorn3** [comment]
It hasnt caused any problems. It just looks wrong.

> From a brief look, lld always outputs S_ATTR_PURE_INSTRUCTIONS for __TEXT,__text, regardless of what the input object files specified.

I guess it doesnt matter if it is used the.
