### ISSUE TITLE
Add TLS standard section

### ISSUE THREAD

**Issue by bjorn3** [gimli-rs/object#138]
`.tdata` for ELF and I think `__DATA,__thread_data` for mach-O, but I don't know what the role of `__DATA,__thread_vars` is yet. Also needs a associated `SectionKind`.

**Comment by philipc** [comment]
`__DATA,__thread_vars` needs to contain [three pointers](https://github.com/llvm-mirror/llvm/blob/2c4ca6832fa6b306ee6a7010bfb80a3f2596f824/lib/CodeGen/AsmPrinter/AsmPrinter.cpp#L612-L615) for each variable. Probably should add a helper method for this.

There's also `.tbss` and `__DATA,__thread_bss`.
