### ISSUE TITLE
Missing constructor symbols in elf

### ISSUE THREAD

**Issue by jayvdb** [gimli-rs/object#149]
When I build some Python packages, and then run `object`'s `nm` on the generated .o files, some symbols are missing

e.g.  https://pypi.org/project/pyzmq/ , https://pypi.org/project/gevent/

```console
> nm build/temp.linux-x86_64-3.7/zmq/backend/cython/message.o | grep __pyx_wrapperbase_3zmq_7backend_6cython_7message_5Frame_2__init__
0000000000000038 C __pyx_wrapperbase_3zmq_7backend_6cython_7message_5Frame_2__init__
> ~/projects/rust/object/target/debug/examples/nm build/temp.linux-x86_64-3.7/zmq/backend/cython/message.o | grep __pyx_wrapperbase_3zmq_7backend_6cython_7message_5Frame_2__init__
0000000000000020 0000000000000038 U __pyx_wrapperbase_3zmq_7backend_6cython_7message_5Frame_2__init__
```

This is blocking https://github.com/indygreg/PyOxidizer/pull/183

https://pypi.org/project/psutil/ appears to be a different problem.

**Comment by philipc** [comment]
Need to add support for common symbols (SHN_COMMON), both for reading and writing.

**Comment by jayvdb** [comment]
I see it at https://github.com/m4b/goblin/blob/495475b9be1ca8d1df0ce40d7dceffcae9cdede4/src/elf/section_header.rs#L80

Is that enough in goblin, or does it also need an enhancement?

**Comment by philipc** [comment]
That's the definition, but that by itself doesn't do anything. It also needs to be handled during [reading](https://github.com/gimli-rs/object/blob/cba3ed4932e4c594c5eab4f5ef6c51838f4a5056/src/read/elf.rs#L562) and [writing](https://github.com/gimli-rs/object/blob/cba3ed4932e4c594c5eab4f5ef6c51838f4a5056/src/write/elf.rs#L423).
