### ISSUE TITLE
Implement symbols

### ISSUE THREAD

**Issue by jrmuizel** [gimli-rs/object#15]
It should be possible to expose a decent cross object symbol api.

**Comment by fitzgen** [comment]
Can you elaborate a bit on what kinds of things you're thinking of here?

There is https://github.com/m4b/cargo-sym, but it doesn't have a programmatic API.

cc @m4b

**Comment by m4b** [comment]
It'd be very fun to design a robust cross platform "Symbol" api.

cargo-sym started to do that, + provides disassembly. It only has a few elf specific items in the trait which could easily be removed.

The rest is teaching the printer how to iterate the symbols and how to disassemble them, similar to objdump style. 

I've been meaning to return to the crate but it didn't receive much attention / uptake / interest so it fell by the wayside.

As @fitzgen says it doesn't have programmatic api but that could easily change; it's essentially already designed and ready for that with the trait, etc. 

I'd be interesting in helping someone fix it up or advising / porting the symbol code to this crate as the programmatic api (which then cargo-sym could consume) but I don't have time to do this by myself unfortunately.

In cargo-sym I'd like to see:

1. Replace my custom, shitty hex printer with @tmoers excellent hexplay
2. Add mach and PE symbols. I believe @willglynn knows much more than me about PE debug symbols and/or regular symbols, and could perhaps provide guidance
3. A good robust Symbol trait
4. Better elf section printer
5. Update most of the crates. Specifically goblin now has all the backends available (mach, PE, elf). I think I'll release goblin 0.11 tonight or over the weekend, which has lots of goodies and fixes 

So yea all of this is possible.

**Comment by willglynn** [comment]
@m4b is correct, I do know some things here :-)

PE executables don't contain symbol tables. They can contain imports and exports, but unlike ELF or Mach-O, they don't ever describe their own symbols, so if you want symbols, you need external data.

MSVC (and now also [LLVM](http://blog.llvm.org/2017/08/llvm-on-windows-now-supports-pdb-debug.html)) produces debug data in PDB format, and among other things, PDBs _do_ contain symbol tables. PDBs are built alongside PE executables, and they may be shipped along with the executable, they may be published to a [symbol server](https://msdn.microsoft.com/en-us/library/windows/desktop/ms680693(v=vs.85).aspx), or they may be lost to the sands of time in which case you're completely SOL. PDB files can be reliably collated with executables using linker-created GUIDs.

Assuming you have a PDB, you can use [my `pdb` crate](https://github.com/willglynn/pdb) to parse the symbol table(s) inside. Note however that the PDB concept of "symbol" differs somewhat from what you might expect on other platforms, as described [by this `pdb::SymbolData` enum](https://docs.rs/pdb/0.1.6/pdb/enum.SymbolData.html). I'm likely to split out all these variants into separate structs before releasing `pdb` 0.2.0, but for the moment that one enum shows you all the different things you might find in a PDB global symbol table.

If all you want is "find this function, disassemble it", that's do-able -- assuming you can supply a matching PDB. If you want something more complicated, that's do-able too, but the semantics quickly become platform dependent. I'd like to clarify this feature with a problem statement.

**Comment by philipc** [comment]
@jrmuizel Currently all the users of this crate that I'm aware of are using it in conjunction with gimli, so they expect DWARF data too. So when you say cross-object API, do you mean only objects that provide DWARF, or do you want something more general that includes PE/PDB too? If you want something that covers PE/PDB too, would you expect the crate to eventually provide a common API for the other info in DWARF/PDB too? I think that PE/PDB support would be rather more ambitious than the intentions of this crate.

**Comment by jrmuizel** [comment]
For PE I'd only expect this crate to give the COFF symbols. That matches what https://github.com/yegord/snowman/blob/cd9edcddf873fc40d7bcb1bb1eae815faedd3a03/src/nc/input/pe/PeParser.cpp#L231 and https://github.com/llvm-mirror/llvm/blob/1020c414d8368e5fc7eca67fff3877b996ea3d71/lib/Object/COFFObjectFile.cpp#L813 do.

**Comment by willglynn** [comment]
@jrmuizel: The COFF symbol table is present for `.obj` object files and for PE files with COFF debugging information. However, as far as I know, every version of MSVC dating back to at least 2002 creates only CodeView (PDB) debugging information when linking executables -- the linker takes all the COFF symbols in the `.obj`s and consolidates them into a PDB when creating a `.exe` or `.dll`.

What problem are you trying to solve with a cross-platform symbol API? `object` users have historically been in a debugging context, so I assumed we were looking at linker outputs as opposed to linker inputs.

**Comment by jrmuizel** [comment]
Ok, it seems like exposing the COFF symbol table isn't going to be of much use unless object/goblin gets support for working with unlinked COFF object files.

My immediate intention when requesting this API was for building a tool for visualizing the code size of compiled code. In this case being able to operate on unlinked COFF object files is valuable but it sounds like to get useful results on exe/dlls it'd have to use the pdb information which feels out of scope for this crate.

**Comment by philipc** [comment]
As an aside, I'm in the process of adding more sizes to ddbug, so if the code visualizations you want would fit in there then feel free to open an issue. Currently it's only sizes from debuginfo, but I intend to include sizes from sections and the symbol table too. My goal is to be able to pinpoint causes of size changes between two binaries.

**Comment by philipc** [comment]
I started looking into this, and it's not easy to provide a generic API that remains useful. Differences between the file formats will leak through any abstraction we provide. Each format has its own flags that mean different things, etc. `llvm-nm` is filled with special handling for the various file formats.

If we had a small well-defined use case then we could limit the API to that. However, I'm not sure that the use case of visualizing code size counts, because Mach-O symbols don't have a size field.

**Comment by philipc** [comment]
llvm-symbolizer calculates the Mach-O symbol size as the distance to the next symbol. We'll need this for addr2line too.
