### ISSUE TITLE
mach-o unimplemented symbol

### ISSUE THREAD

**Issue by jayvdb** [gimli-rs/object#158]
In the same setup as https://github.com/gimli-rs/object/issues/149 , Cython modules in `gevent` fail to be parsed on mach-o with the error
> unimplemented symbol Symbol { name: [95, 95, 95, 112, 121, 120, 95, 109, 111, 100, 117, 108, 101, 95, 105, 115, 95, 109, 97, 105, 110, 95, 103, 101, 118, 101, 110, 116, 95, 95, 95, 113, 117, 101, 117, 101], value: 0, size: 0, kind: Unknown, scope: Dynamic, weak: false, section: Some(SectionId(2)) }"'

That name is `___pyx_module_is_main_gevent___queue`.

This symbol comes from Cython generated wrapper code

```console
cython$ git grep is_main
Cython/Compiler/ModuleNode.py:        module_is_main = "%s%s" % (Naming.module_is_main, self.full_module_name.replace('.', '__'))
Cython/Compiler/ModuleNode.py:        code.putln("extern int %s;" % module_is_main)
Cython/Compiler/ModuleNode.py:        code.putln("int %s = 0;" % module_is_main)
Cython/Compiler/ModuleNode.py:        code.putln("if (%s%s) {" % (Naming.module_is_main, self.full_module_name.replace('.', '__')))
Cython/Compiler/ModuleNode.py:        module_is_main = "%s%s" % (Naming.module_is_main, self.full_module_name.replace('.', '__'))
Cython/Compiler/ModuleNode.py:                module_is_main=module_is_main,
Cython/Compiler/Naming.py:module_is_main   = pyrex_prefix + "module_is_main_"
Cython/Utility/Embed.c:      %(module_is_main)s = 1;
bin/cython_freeze:    print("\nextern int __pyx_module_is_main_%s;" % modules[0])
bin/cython_freeze:    __pyx_module_is_main_%(main)s = 1;
```

The command to compile the offending .o is
```console
$ clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/var/folders/dd/xb3jz0tj133_hgnvdttctwxc0000gn/T/tmp9f1_qys4/tools/deps/include -I/var/folders/dd/xb3jz0tj133_hgnvdttctwxc0000gn/T/tmp9f1_qys4/tools/deps/include/ncurses -I/var/folders/dd/xb3jz0tj133_hgnvdttctwxc0000gn/T/tmp9f1_qys4/tools/deps/lib/libffi-3.2.1/include -I/var/folders/dd/xb3jz0tj133_hgnvdttctwxc0000gn/T/tmp9f1_qys4/tools/deps/include/uuid -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks -Werror=unguarded-availability-new -I/usr/local/opt/openssl@1.1/include -U__llvm__ -I/Users/runner/pyapp/build/target/x86_64-apple-darwin/debug/pyoxidizer/hacked_base/include/python3.7m -I/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pyoxidizer-temp-venv.2zNoVZYSf6Py/venv/include/site/python3.7 -Ideps -I/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pyoxidizer-temp-venv.2zNoVZYSf6Py/venv/include -I/Users/runner/pyapp/build/target/x86_64-apple-darwin/debug/pyoxidizer/hacked_base/include/python3.7m -I/install/include/python3.7m -c src/gevent/queue.c -o build/temp.macosx-10.9-x86_64-3.7/src/gevent/queue.o
```

Removing `-g`, `-O3` and `-fPIC` didnt seem to make any difference.
Using gcc instead of clang also didnt fix it.

nm reports it as

> 2019-11-27T11:55:33.9006300Z     000000000005fd30 S ___pyx_module_is_main_gevent___queue

nm manpage says this is

> The symbol is in an uninitialized or zero-initialized data section for small objects.

An initial attempt at using options -mno-extern-sdata, -mno-local-sdata & -mno-embedded-sdata didnt work - they appeared in unused arguments warnings.  It sounds like that might work, so I'll re-attempt that as a temporary workaround.

**Comment by philipc** [comment]
Which section corresponds to `SectionId(2)`?

**Comment by jayvdb** [comment]
Hope this helps

```console
$ objdump --section-headers build/temp.macosx-10.9-x86_64-3.7/src/gevent/queue.o
build/temp.macosx-10.9-x86_64-3.7/src/gevent/queue.o:	file format Mach-O 64-bit x86-64

0 __text        0005273c 0000000000000000 TEXT
1 __common      00000004 000000000005fd30 BSS
2 __data        00005078 0000000000052740 DATA
3 __cstring     00001e1b 00000000000577b8 DATA
4 __const       00000ce0 00000000000595e0 DATA
5 __bss         00001100 000000000005fd40 BSS
6 __compact_unwind 00002820 000000000005a2c0 DATA
7 __eh_frame    00003250 000000000005cae0 DATA

objdump -t build/temp.macosx-10.9-x86_64-3.7/src/gevent/queue.o

...
0000000000056950 l       __DATA,__data	___pyx_getsets_6gevent_6_queue_Channel
0000000000000000 g     F __TEXT,__text	_PyInit__queue
000000000005fd30 g       __DATA,__common	___pyx_module_is_main_gevent___queue
0000000000000000         *UND*	_PyBaseObject_Type
...
```

I think it would be useful for the `object` error strings say which section name, as it looks like `object` section 0 is often not the same as `objdump` section 0 - I have seen `object` often includes an unnamed Metadata section which `objdump` doesnt include.

**Comment by philipc** [comment]
So it's a common symbol again, same as #149. I'll work on implementing this, but for now you can try `-fno-common`. Whether this works depends on whether there are duplicate definitions of the common symbol.

> I think it would be useful for the object error strings say which section name, as it looks like object section 0 is often not the same as objdump section 0 - I have seen object often includes an unnamed Metadata section which objdump doesnt include.

Yeah, this is the null ELF section. readelf shows it too though.

**Comment by jayvdb** [comment]
There will usually be only one definition of these symbols -- they are given a unique name by the Cython generator, which includes the name of package, not just the compiled module name, so very rare it will be in conflict.

Adding `-fno-common` didnt appear to help.

**Comment by jayvdb** [comment]
Adding `-fno-common` did work on Linux with gcc as a workaround for https://github.com/gimli-rs/object/issues/149 .

**Comment by philipc** [comment]
Are you able to provide a sample of the object file? (I primarily need this for Mach-O since I don't have any macos machines, but it would be helpful for the COFF issue too.)

**Comment by jayvdb** [comment]
I suspect a sample of this problem might be found in the objects in https://github.com/indygreg/python-build-standalone/releases/download/20191025/cpython-3.7.5-macos-20191026T0535.tar.zst .  I'll try to find one later today.

**Comment by jayvdb** [comment]
Did a quick script using the example `objcopy` and binutils `nm -g` to look for unparsable and extern sym differences in the above archive `build/Python`

Unparsable:
- build/Python/dtoa.o
- build/Python/getopt.o
- build/Python/modsupport.o
- build/Python/pathconfig.o
- build/Python/pyhash.o
- build/Python/pylifecycle.o

getopt.o looks the most similar

> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "unimplemented symbol Symbol { name: [95, 95, 80, 121, 79, 83, 95, 111, 112, 116, 97, 114, 103], value: 0, size: 0, kind: Unknown, scope: Dynamic, weak: false, section: Some(SectionId(2)) }"', src/libcore/result.rs:1084:5

That is symbol `__PyOS_optarg`, which is defined as `extern wchar_t *_PyOS_optarg` ,and section headers looks like
```console
Sections:
Idx Name          Size      VMA               LMA               File off  Algn
  0 .text         000003a4  0000000000000000  0000000000000000  00000720  2**4
                  CONTENTS, ALLOC, LOAD, RELOC, CODE
  1 .data         00000010  00000000000003a8  00000000000003a8  00000ac8  2**3
                  CONTENTS, ALLOC, LOAD, RELOC, DATA
  2 __DATA.__common 00000008  0000000000001318  0000000000001318  00000000  2**3
                  ALLOC
  3 .const        00000054  00000000000003b8  00000000000003b8  00000ad8  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  4 .cstring      000000a7  000000000000040c  000000000000040c  00000b2c  2**0
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  5 .debug_str    00000157  00000000000004b3  00000000000004b3  00000bd3  2**0
                  CONTENTS, DEBUGGING
...
```
