### ISSUE TITLE
pe/coff don't handle IMAGE_SCN_LNK_NRELOC_OVFL 

### ISSUE THREAD

**Issue by philipc** [gimli-rs/object#177]
This is required when there are more than 65535 relocations.

**Comment by osiewicz** [comment]
I want to tackle write support in `write/coff` that you've mentioned [here](https://github.com/gimli-rs/object/pull/399#discussion_r751824898) - I have two questions though:
1. If I understand the code & API correctly, we pretty much need to just modify [this code](https://github.com/gimli-rs/object/blob/master/src/write/coff.rs#L374) and the following relocation entry writing?
2. Should I open a separate ticket for `write/coff` support or can we stick to that one?

**Comment by philipc** [comment]
Sorry, I had already started on the write support (see #401), but thanks for following up on that. No need to create an issue for things that are immediately being fixed, that's needless busywork.
