### ISSUE TITLE
elf: global delimiter in sh_info technically points past global symbols

### ISSUE THREAD

**Issue by m4b** [gimli-rs/object#179]
While poking around with https://github.com/bytecodealliance/cranelift/issues/1354

I noticed there is a global symbol interleaved with local symbols in the symtab. The linker seems to be ok with it (probably because it's a `FILE` type, or has an `ABS` value?), and it seems like you're doing the right thing with: https://github.com/gimli-rs/object/blob/a70c9e60efb1e5c56c8f61b8aee04a47485ab82b/src/write/elf.rs#L687

But I do technically see a global before the delimiter specified in `sh_info` (in this case 0x4)
```
Syms(6):
               Addr   Bind       Type        Symbol                               Size    Section      Other  
                 0    LOCAL      NOTYPE                                           0x0                  0x0    
                 0    GLOBAL     FILE        /home/m4b/projects/faerie/rodata.c   0x0     ABS          0x0    
                10    LOCAL      OBJECT      index_page                           0x8     .rodata(1)   0x0    
                 0    LOCAL      OBJECT      str.10                               0xb     .rodata(1)   0x0    
                 0    GLOBAL     NOTYPE      puts                                 0x0                  0x0    
                 0    GLOBAL     FUNC        main                                 0x20    .text(3)     0x0  
```

In this case, your `sh_info` is emitted with a `0x4`, which points it at `puts`, which I believe is correct/desired. However, the global before this referring to the filename may or may not be "out of spec"?

But I'm not sure. Just posting this issue here, just in case. Investigating other object files, I don't find local/global/local interleaves (and in past, they have caused really hard to track bugs: https://github.com/m4b/faerie/blob/f74a4bdc2d05a4ec593dcfc39bad93fde751c882/src/elf.rs#L876)

**Comment by philipc** [comment]
Yeah that does look weird, thanks for the issue. The thing is that the `FILE` symbol is meant to come before all the symbols for that file, so not sure how that ties in with the local/group ordering. I'll look into it later.

**Comment by m4b** [comment]
Yea looks like other compilers make `FILE` local, e.g., here's clang:

```
Syms(8):
               Addr   Bind       Type        Symbol       Size    Section             Other  
                 0    LOCAL      NOTYPE                   0x0                         0x0    
                 0    LOCAL      FILE        rodata.c     0x0     ABS                 0x0    
                 0    LOCAL      OBJECT      index_page   0x8     .data(4)            0x0    
                 0    LOCAL      SECTION                  0x0     .text(2)            0x0    
                 0    LOCAL      SECTION                  0x0     .data(4)            0x0    
                 0    LOCAL      SECTION                  0x0     .rodata.str1.1(6)   0x0    
                 0    GLOBAL     FUNC        main         0x21    .text(2)            0x0    
                 0    GLOBAL     NOTYPE      puts         0x0                         0x0    
```

If its not too hard, for more future looking, also recommend removing the absolute paths in the symbol name for the file (like e.g., clang does above). Absolute paths become really annoying to deal with in build systems like bazel, which cause non-deterministic builds and cache misses. Just something to think about in the future :)

**Comment by m4b** [comment]
RE absolute paths, looks like this is based on invocation location, ditto with clang, i can't remember what bazel does to avoid this, probably either spawns in location, or last i recall, clang had a -fprefix-map option or something, anyway :D

**Comment by philipc** [comment]
> also recommend removing the absolute paths in the symbol name for the file

Unless this is something that needs to be handled differently between ELF and COFF, then that is up to the caller to do.
