### ISSUE TITLE
[ELF] Include dynamic_symbols in symbol_map

### ISSUE THREAD

**Issue by bjorn3** [gimli-rs/object#188]

**Comment by philipc** [comment]
Can you give more detail on when this is useful? Do the dynamic symbols contain information that is missing from the other symbols?

**Comment by bjorn3** [comment]
For for example `ld.so` the symbols list is empty, while the `dynamic_symbols` list does is not.

**Comment by philipc** [comment]
Maybe you can install the package containing the debug symbols for `ld.so`? That will give a more complete result.

**Comment by bjorn3** [comment]
1. I want my program to be as robust around missing information as possible
2. How can installing a different file suddenly add symbols to ld.so itself?

**Comment by philipc** [comment]
> I want my program to be as robust around missing information as possible

That's reasonable, but I expect it will still be missing a lot of information.

So the dynamic symbols only need to be included if the debug symbols are missing?

> How can installing a different file suddenly add symbols to ld.so itself?

It doesn't, but your program will be able to find the different file using the build id. If this is for creating backtraces for example, then you should be doing that anyway to find the DWARF.

**Comment by bjorn3** [comment]
> That's reasonable, but I expect it will still be missing a lot of information.

True, but something is better than nothing.

> So the dynamic symbols only need to be included if the debug symbols are missing?

Using `object.symbols().iter().chain(object.dynamic_symbols()).collect()` followed by sort and dedup when constructing the SymbolMap should work, right?

> It doesn't, but your program will be able to find the different file using the build id. If this is for creating backtraces for example, then you should be doing that anyway to find the DWARF.

+1 though I don't yet handle any DWARF at all.

**Comment by philipc** [comment]
I am considering changing `dynamic_symbols` because it doesn't fit other file formats (#182).

By the way, which information do you need from the symbol map? Is address/size/name enough?

**Comment by bjorn3** [comment]
> Is address/size/name enough?

Yes. I am currently just combining `symbols()` and `dynamic_symbols()` (cached of course) and then searching through it, but being able to use SymbolMap is nicer.

**Comment by philipc** [comment]
Looking at the [libbacktrace source](https://github.com/rust-lang-nursery/libbacktrace/blob/f4d02bbdbf8a2c5a31f0801dfef597a86caad9e3/elf.c#L2920-L2922), it uses in order of priority:
- dwarf
- debug symbols
- dynamic symbols

It never uses more than one of these though, and I see no reason why we would need to. So I'm inclined to support the same thing initially, but if that proves to be insufficient then we can change it later.

I'll be working on this as part of https://github.com/rust-lang/backtrace-rs/issues/287. This will probably include a rework of `Symbol` and `SymbolMap` (changing `Symbol` to a trait, and changing `SymbolMap` to be only address/size/name).

**Comment by philipc** [comment]
Fixed in #250 (We now use the dynamic symbols if there are no debugging symbols.)
