### ISSUE TITLE
WebAssembly reader should recognise imports/exports

### ISSUE THREAD

**Issue by RReverser** [gimli-rs/object#196]
Let's take the following example to demonstrate various types of symbols:

```c
extern int f();

static int g() {
	return 42;
}

int h() {
	return f() + g();
}

int h2() __attribute__((weak, alias("h")));
```

If we compile it to an ELF object on Linux and run via `nm` example like this:

```bash
$ gcc temp.c -o temp.o -c -g
$ cargo run --example nm temp.o
```

then the output will contain all symbols with corresponding kinds:

```
Debugging symbols:
                 0000000000000000 U
0000000000000000 000000000000000b t g
000000000000000b 0000000000000028 T h
                 0000000000000000 U _GLOBAL_OFFSET_TABLE_
                 0000000000000000 U f
000000000000000b 0000000000000028 T h2
```

Now, if I instead compile this file to WebAssembly and dump it:

```bash
$ clang temp.c -g -target wasm32 -o temp.wasm -Wl,--no-entry,--export-all,--allow-undefined -nostdlib
$ cargo run --example nm temp.wasm
```

then I see only defined functions, but not all symbols in the same sense as ELF (for example, no `h2`) and no kind info either:

```
Debugging symbols:
0000000000000000 0000000000000000 ? f
0000000000000001 0000000000000000 ? __wasm_call_ctors
0000000000000002 0000000000000000 ? h
0000000000000003 0000000000000000 ? g

Dynamic symbols:
```

Obviously, the actual underlying reason is simply that reading import/export sections of Wasm is not currently implemented in Wasm reader, but I thought it would be helpful to provide an example that would demonstrate the difference and `nm` example seemed like a good way to provide the dump.

**Comment by RReverser** [comment]
Another issue that is visible from this dump (not sure if to raise separately or not) is that address of each function is set to an incrementing number, but it needs to be an actual offset of the function code.

Just like in ELF, this is important, for example, for matching functions to their DWARF info.

**Comment by philipc** [comment]
The current status of the Wasm reader is that it exists only to support the dwarfdump example in gimli. I don't know a lot about Wasm, but my expectation is that it is rather different from ELF/Mach-O/PE. If it can be extended to support the same API as those (or a subset of that API), then those changes would be welcome, but I don't want its differences to result in major changes to the API provided for the other file formats. Of course, if those changes are an improvement for the other file formats too then that's great.

Note that currently we're using a custom parser, but if we're going to make extensive changes to the parser then I think it needs to switch to `wasmparser` instead (discussed in #185).

What application are you intending to use this for that would benefit from the unified API this crate provides?

**Comment by RReverser** [comment]
> but I don't want its differences to result in major changes to the API provided for the other file formats

Yeah, I don't think that this will require any extensive changes to API (or maybe even none at all), only a change to what is considered a symbol in Wasm.

> then I think it needs to switch to wasmparser instead (discussed in #185)

Agreed.

> What application are you intending to use this for that would benefit from the unified API this crate provides?

I want to be able to consistently extract debug info, similarly to ddbug, but only for public symbols (imports and exports). Currently there is no way to distinguish these from others in Wasm, so I thought the best place to add it would be in `object` crate which already does this for other object types.
