### ISSUE TITLE
Don't use Vec::with_capacity with untrusted lengths

### ISSUE THREAD

**Issue by philipc** [gimli-rs/object#204]
This is currently used for ELF decompression, and even though it is good for performance, it allows malformed files to cause allocation of large amounts of memory.

**Comment by bjorn3** [comment]
Maybe limit it to the file size or some foxed value?

**Comment by fitzgen** [comment]
Could also consider polyfilling

```rust
let mut v: Vec<u8> = vec![];
v.try_reserve(n)?;
```

via

```rust
let ptr = std::alloc::alloc(Layout::from_size_align_unchecked(n, 1));
if ptr.is_null() {
    // failure case...
}
let v = Vec::from_raw_parts(ptr, 0, n);
```

This would at least avoid untrusted code easily triggering OOMs, but not enforce an upper limit.

**Comment by philipc** [comment]
My initial thought was we could grow the vec as we decompress instead of reserving it all at once, but while that makes it harder to occur, it's still possible for it to trigger OOM. Choosing a fixed value is hard (the file size is too small to use). That `try_reserve` sounds like the best we could do.

I'm not sure how much of a problem this is to be concerned about. e.g. if you're using this for compressed debug information then you're probably executing the code in the file already.

**Comment by symphorien** [comment]
I was bitten by this: a corrupted elf file that attempted to allocate 5 exabytes of memory when object tries to obtain the buildid. I opened a PR in https://github.com/gimli-rs/object/pull/630 to at least check that size are smaller than the files we are reading from when allocating a buffer to read into.
