### ISSUE TITLE
write/coff: object::write::SymbolSection::Undefined mapped to IMAGE_SYM_CLASS_EXTERNAL_DEF?

### ISSUE THREAD

**Issue by wwylele** [gimli-rs/object#209]
I am not sure if this is a problem in the library or my mistake in understanding. I am using the library to generate an object file which is ready for linking later. When I wanted to import a external function defined in other library, I declared a symbol with `SymbolSection::Undefined` like this:
```
obj.add_symbol(object::write::Symbol {
            name,
            value: 0,
            size: 0,
            kind: object::SymbolKind::Text,
            scope: object::SymbolScope::Linkage,
            weak: false,
            section: object::write::SymbolSection::Undefined,
            flags: object::SymbolFlags::None,
        })
```
This works well in linux/ELF, but failed for windows/COFF. The MSVC linker didn't complain, but the final executable silently crashes. 

Interestingly, when I changed `object::write::SymbolSection::Undefined` to `object::write::SymbolSection::Common`, it worked in both systems. But I know `Common` has a slightly different meaning in elf and I don't want that.

I looked into the code and found that the difference between `Undefined` and `Common` for COFF is in the storage class.
https://github.com/gimli-rs/object/blob/267199e410ef2a06d955f7ee1ad6410e47e1a206/src/write/coff.rs#L471-L472

I also looked up Microsoft documentation: https://docs.microsoft.com/en-us/windows/win32/debug/pe-format Confusingly, the explanation between `IMAGE_SYM_CLASS_EXTERNAL` and  `IMAGE_SYM_CLASS_EXTERNAL_DEF` are awfully similar. However, the doc does mention that:
> Although the traditional COFF format uses many storage-class values, Microsoft tools rely on Visual C++ debug format for most symbolic information and generally use only four storage-class values: EXTERNAL (2), STATIC (3), FUNCTION (101), and STATIC (103). Except in the second column heading below, "Value" should be taken to mean the Value field of the symbol record (whose interpretation depends on the number found as the storage class).

This implies that Microsoft linker might not understand `IMAGE_SYM_CLASS_EXTERNAL_DEF` at all, and `object::write::SymbolSection::Undefined` should use `IMAGE_SYM_CLASS_EXTERNAL` instead. I also l searched llvm source code to reinforce my understanding. There is reference to `EXTERNAL` but no reference to `EXTERNAL_DEF` in their source code 
https://github.com/llvm-mirror/llvm/blob/d0f842f84bf4e0b6973a572faeaf3847c4d7e244/lib/MC/WinCOFFObjectWriter.cpp#L411

**Comment by philipc** [comment]
Yep that definitely is wrong. Based on the symbols that gcc generates, the only difference between common and undefined symbols should be that common symbols use their size as the value.
I wonder what made me think that `IMAGE_SYM_CLASS_EXTERNAL_DEF` was used, because I've done the same thing for reading too.
