### ISSUE TITLE
write: redesign relocation kinds

### ISSUE THREAD

**Issue by philipc** [gimli-rs/object#214]
I think that relocation kinds are a bit too artificial, and we should do something simpler. Currently relocation kinds are a combination of a `RelocationKind` and a `RelocationEncoding`. I think we should switch to using the native relocation values instead.

The primary benefit of the current scheme is that it allows you to write architecture independent code in some cases (mostly in data sections, such as DWARF). We can still support this by keeping the concept of a `RelocationKind` and providing a helper API that returns the native relocation value for a given `RelocationKind`. This keeps the benefit without requiring us to artificially classify all relocations into `RelocationKind`+`RelocationEncoding`.

There's also a bit of fixup logic in `Object::add_relocation`, and we would need to make sure this is manageable when using native relocation values (it might result in a lot of architecture-dependent checks).

As part of this, only relocations that `object` knows about would be supported for ELF `SHT_REL` sections, since we need to know how to write the implicit addend.

**Comment by philipc** [comment]
LLD defines ELF relocations as:
```C
struct Relocation {
  RelExpr expr;
  RelType type;
  uint64_t offset;
  int64_t addend;
  Symbol *sym;
};
```
`RelType` is the raw ELF relocation value. `RelExpr` is very similar to `object::RelocationKind`, and is derived from the `RelType` (and rarely other information too).

**Comment by Amanieu** [comment]
I'm using `object` for parsing ELF files and find that `RelocationKind` is very brittle. The main issue is that if `object` learns to handle a new relocation type then my existing code which was previously handling it using `RelocationKind::Elf` will stop working.

A better API would be to expose the raw relocation info separately from the platform-independent relocation type. The platform-independent relocation could be `None` to indicate an unrecognized relocation type.

**Comment by philipc** [comment]
I think the read API will be easy to change in the manner you suggest. I'd like to do that at the same time as the write API change. Your comment gives me confidence that this is the right change to be making.

**Comment by bjorn3** [comment]
Cranelift has a combination of architecture independent (absolute and relative relocations of various sizes) and architecture dependent (for example 21bit arm relative relocations) relocation kinds, but all are object file format independent. It would be nice if something similar could be preserved so that cranelift-object can stay object file format and architecture independent.

**Comment by philipc** [comment]
The architecture/format dependent code to convert a relocation kind to a raw relocation type can stay in `object`, but `cranelift-object` will need an extra step to call that code.
