### ISSUE TITLE
Implement relocations for dynamic symbols in elf

### ISSUE THREAD

**Issue by matprec** [gimli-rs/object#227]
I'm interested in implementing support for reading relocations of dynamic symbols in elf.

https://github.com/gimli-rs/object/blob/3879fc51fca97cbbe87e8fc94b1ff2098c46e149/src/read/elf/relocation.rs#L36

Would you mind giving me some guidance?

I'll start collecting resources on the topic. I have some familiarity with elf, but have yet to research relocations :)

**Comment by philipc** [comment]
The hardest part of this is deciding what the API for it should be, and designing that is best done with a use case in mind. How are you planning to use the dynamic relocations?

**Comment by matprec** [comment]
I want to identify and annotate memory locations / jump targets within disassembled code. I've already implemented support for symbols within the binary, but can't handle dynamic symbols yet because they have to be relocated. In terms of output, if you think of `objdump -d bin` you'll get pretty close.

From an api consumer point of view, the end goal for me would be a more elaborate symbol lookup/map api, where you provide an address and get the closest symbol (+ offset). Although i'm not sure if this breaks the scope of this library. Let me know if you'd be interested in such an api :)
I think that this is still a step to far for now and we should concentrate on extracting (dynamic) relocations first.

At first, parsing the `rela.dyn` and `rela.plt` section and getting an iterator over the entries.
I think such an api would be desirable on its own.

This should probably suffice, although i haven't reconstructed the whole resolution mechanism yet.

For designing the api, it would make sense to dogfood the api and compare the output to objdump on various binaries of different compilers. This should give as a good overview on what works and what not.

**Comment by philipc** [comment]
> I want to identify and annotate memory locations / jump targets within disassembled code. I've already implemented support for symbols within the binary, but can't handle dynamic symbols yet because they have to be relocated. In terms of output, if you think of objdump -d bin you'll get pretty close.

I've actually done a little bit of this sort of thing, e.g. https://github.com/gimli-rs/ddbug/commit/236a12392cb1ca9004341b98323e619eca1762f9
I think that was only working on object files though, but might still be of interest to you.

> From an api consumer point of view, the end goal for me would be a more elaborate symbol lookup/map api, where you provide an address and get the closest symbol (+ offset). Although i'm not sure if this breaks the scope of this library. Let me know if you'd be interested in such an api :)

There is already `SymbolMap` for this. However, I'm actually working on improving that right now to support the needs of `backtrace-rs` which currently has its own implementation. Any feedback on what it lacks currently would be useful.

> At first, parsing the rela.dyn and rela.plt section and getting an iterator over the entries.
I think such an api would be desirable on its own.

Ok, this isn't something I'm familiar with yet, so I'll give my thoughts but this might be all a bit vague and wrong.

The code you linked is for `elf::RelocationSections`. The current API model is that we provide relocations that apply to a single section, and `RelocationSections` is used to figure out which relocation sections are associated with a section. I suspect that what you need is different from that, and you won't need to modify `RelocationSections` at all.

Do you care about which section contains the relocation? Is it enough to provide a single iterator for all relocations in the file? This reason I am asking this is because Mach-O and PE/COFF don't have separate relocation sections, so an iterator over the entries in a relocation section won't make sense for them.

**Comment by philipc** [comment]
So what we might want is to have `Object::relocations` and `Object::dynamic_relocations`, and the symbols these refer to will be the symbols given by `Object::symbols` and `Object::dynamic_symbols` respectively.

**Comment by matprec** [comment]
> I've actually done a little bit of this sort of thing, e.g. gimli-rs/ddbug@236a123

Very interesting, i'll have a look, thank you!

> There is already SymbolMap for this.

I was under the impression that this would only return a symbol for the precise address, but now that i took a look at the implementation i stand corrected :)
Offset can then easily be calculated using the returned symbols address. I'll send a quick PR to stress this in the documentation!

> Ok, this isn't something I'm familiar with yet

Me neither, i have yet to find a comprehensive source on this topic. The spec is a good start but when interpreting and trying to understand the full mechanism on an example, i quickly find myself going down a rabbit hole on various blogs.

> I suspect that what you need is different from that, and you won't need to modify RelocationSections at all.

You are completely right, good catch!

> Is it enough to provide a single iterator for all relocations in the file?

> So what we might want is to have Object::relocations and Object::dynamic_relocations, and the symbols these refer to will be the symbols given by Object::symbols and Object::dynamic_symbols respectively.

The proposed solution seems fine for me :) I've wondered if it might make sense to include the section from where the relocation might come from, as per the [system v abi](http://www.sco.com/developers/gabi/2003-12-17/ch4.sheader.html) the section name for the relocation table *conventionally* indicates the section its entries apply to. I've read that this distinction is superficial and mainly for ease of implementation for linkers and i can't think of a benefit for api consumers, since the target symbol is unambiguous.

**Comment by matprec** [comment]
For future reference, apart from the [linux base specification](https://refspecs.linuxfoundation.org/lsb.shtml) (core area), i've found [this site](https://www.cs.stevens.edu/~jschauma/631/elf.html) helpful.

**Comment by philipc** [comment]
> I've wondered if it might make sense to include the section from where the relocation might come from, as per the system v abi the section name for the relocation table conventionally indicates the section its entries apply to. I've read that this distinction is superficial and mainly for ease of implementation for linkers and i can't think of a benefit for api consumers, since the target symbol is unambiguous.

You don't need to use the section name, `sh_info` contains the section index (see Figure 4-12). We can include that if needed, but doing that means we need to start iterating relocations within a section (because `sh_info` is a section field), and that doesn't make sense for the other file formats. I guess we could include it in every relocation itself, but that's not ideal other. My understanding is the dynamic linker doesn't need to know this relation though, so for what you are trying to achieve, you probably don't need to know it other, so let's try to leave this out.

**Comment by matprec** [comment]
> The code you linked is for elf::RelocationSections. The current API model is that we provide relocations that apply to a single section, and RelocationSections is used to figure out which relocation sections are associated with a section. I suspect that what you need is different from that, and you won't need to modify RelocationSections at all.

Now that i've studied the codebase closer, i think it would make sense to extract the logic from `RelocationSections`, as it already does most of the necessary work.

I've identified two key regions in the code for this to work:

1. The relocation sections only get requested for the (static) symbol table section.

https://github.com/gimli-rs/object/blob/1dc0960a337dc44e71adcf518826cdaa76a08145/src/read/elf/file.rs#L45-L49

And this check rejects every relocation section that does not reference the requested section.

https://github.com/gimli-rs/object/blob/1dc0960a337dc44e71adcf518826cdaa76a08145/src/read/elf/relocation.rs#L38-L40

2. Most of the time, the following check will reject `rela.dyn` sections. The spec is a little thin on the details here and i couldn't find any source on this, but i didn't try too hard.
According to [Figure 4-12](http://www.sco.com/developers/gabi/2003-12-17/ch4.sheader.html#sh_link), sh_info does not identify dynamic sections, but which section it applies to. According to [this thread](https://sourceware.org/bugzilla/show_bug.cgi?id=22587) on the binutils but tracker, a section is not given when it is not needed. This coincidentally happens for `rela.dyn` sections, as they mostly contain `R_X86_64_GLOB_DAT` and `R_X86_64_RELATIVE` relocations which do not need symbol indices. In my understanding, this means the check should be orthogonal to its original intention and can be removed.
https://github.com/gimli-rs/object/blob/1dc0960a337dc44e71adcf518826cdaa76a08145/src/read/elf/relocation.rs#L43-L46

I propose the following strategy:
1. Refactor and extract the logic from `RelocationSections`
2. remove the `sh_info == 0` check
3. Create the `object.relocations()` and `object.dynamic_relocations()` iterators.

**Comment by philipc** [comment]
> Now that i've studied the codebase closer, i think it would make sense to extract the logic from RelocationSections, as it already does most of the necessary work.

Hmm, I actually think it does very little of what you need. It's building up a mapping from text/data sections to relocation sections. But you don't need that mapping. Instead, why can't you simply iterate over all of the sections?

That is, you only need this part:

```rust
        for (index, section) in sections.iter().enumerate().rev() {
            let sh_type = section.sh_type(endian);
            if sh_type == elf::SHT_REL || sh_type == elf::SHT_RELA {
```

and that is simple enough to not require extracting into common code.

> In my understanding, this means the check should be orthogonal to its original intention and can be removed.

No, the purpose of this code is to find only relocations that apply to sections. That is, those relocations that use section offsets rather than virtual addresses. So the comment may be using the wrong terminology, but I think the check is correct. Additionally, the code relies on the section indices being non-zero:
https://github.com/gimli-rs/object/blob/1dc0960a337dc44e71adcf518826cdaa76a08145/src/read/elf/relocation.rs#L65

**Comment by matprec** [comment]
> you need a check to see if it is using the debugging symbols or the dynamic symbols.

You mean checking if the associated symbol table is of type `SHT_SYMTAB` or `SHT_DYNSYM`?

> No, the purpose of this code is to find only relocations that apply to sections. That is, those relocations that use section offsets rather than virtual addresses.

I see, this makes much more sense now.

Thank you very much for your input, this helps me a lot :)

**Comment by philipc** [comment]
> You mean checking if the associated symbol table is of type SHT_SYMTAB or SHT_DYNSYM?

Yeah, which is done by checking if it matches `symbol_section` (I edited that comment a few times).

**Comment by matprec** [comment]
> Mach-O and PE/COFF don't have separate relocation sections

1. I've looked into Mach-O today and i'm not sure how to go forward there:
There are no standalone sections for relocations, just offsets within the sectionheader for a given section. Are these only used for symbol tables? If not, what do these relocations apply to?

2. In the Mach-O api for dynamic symbols, the symbols iterator is returned but it is not filtered or anything. I understand that the symbol table is the same and doesn't differentiate, and the dynamic symbol table are just indices into the "normal" table. But the `LC_DYSYMTAB` is never read or evaluated/accessible in any way, would you mind elaborating on that decision? How would you differentiate?

https://github.com/gimli-rs/object/blob/1dc0960a337dc44e71adcf518826cdaa76a08145/src/read/macho/file.rs#L171-L183

In a naive way, i'd say implementing the relocation iterator would be as simple as the following pseudo code
```rust
macho_file
    .sections()
    .map(Section::relocations)
    .flatten()
```

But that would assume that there are only relocations that apply to symbols (1.) and it wouldn't differentiate between dynamic or debugging symbols at all (2).

**Comment by philipc** [comment]
I think `dynamic_symbols` for Mach-O is wrong currently. It was an attempt to do "something" when implementing the ELF support, but I haven't used it myself, and I have no idea if anyone else has. This is part of #182. I think the changes needed here are:
- `dynamic_symbols` should only return symbols for file formats that have a second symbol table that contains symbols used in dynamic linking. For Mach-O, this would return nothing.
- we add new `imports` and `exports` APIs

I think these changes should be separate from this issue though.

Going back to what I said earlier:

> So what we might want is to have Object::relocations and Object::dynamic_relocations, and the symbols these refer to will be the symbols given by Object::symbols and Object::dynamic_symbols respectively.

Since Mach-O won't have `dynamic_symbols`, it won't have `dynamic_relocations` either.

**Comment by matprec** [comment]
I'm thinking about renaming `ElfRelocationIterator`, since it is much more advanced than the name suggests (iterate over the relocation(section)s that apply to a particular section). I'd like to free that name for the iterator for the new api, as it is much simpler (give me all (dynamic) relocations in the file).

Options that i've come up with (in no particular order):
 - `ElfRelocationFilter`
 - `ElfAppliedRelocations`
 - `ElfRelevantRelocations`

What do you think? If you prefer to leave the name as they are now, that's fine for me as well.

**Comment by philipc** [comment]
I'm a bit carefree with breaking changes :) Changing it would be ok if it's significantly better for the long term, and I doubt anyone is using `ElfRelocationIterator` specifically yet. A possible name would be `ElfSectionRelocationIterator`.

**Comment by viveksjain** [comment]
I have a very similar use case - need a mapping from (plt) address to name to be able to display it. Would love to use it if it's available.

**Comment by philipc** [comment]
@matprec How far did you get with this? I'm close to merging a PR (#250) that is probably going to conflict with whatever work you had done. If you no longer have time to work on this, then I would be happy to finish it off, if you can publish a branch with what you have done.

**Comment by matprec** [comment]
@philipc I'm sorry for not following up on this, my priorities shifted due to working on my thesis.

I'm currently don't have access to my dev system, but i could arrange some time. As far as i remember, i had working elf support but i got stuck with research on coff.

**Comment by matprec** [comment]
@philipc In any case, it would probably be better to merge #250 first and i rebase my work on top of that.

**Comment by viveksjain** [comment]
Any updates here? Thanks

**Comment by philipc** [comment]
@matprec Do you think you'll be able to publish your current work somehow? It doesn't need to be finished or rebased.

**Comment by philipc** [comment]
I've been looking into this a little, and I don't think that exposing a unified API for dynamic relocations is going to be the best way of doing this. The unified API is meant to provide an abstraction at a level where you need to know little about the underlying format, but dynamic relocations aren't really at that level.

I think the goal of this feature is to provide a way to determine the symbol name associated with each PLT stub, and knowing the dynamic relocations isn't enough to do that. You also need to know how those relocations are associated with the PLT stubs, and that is becoming specific to each file format.

So I think the unified API should provide an iterator that for each PLT entry gives:
- the address of the stub in .plt
- the address of the relocation
- the symbol name from the relocation

This is something that would make sense to know for both ELF and Mach-O (and maybe also the PE import address table). Does that sound like it would cover your needs?

If instead you want something lower level, then we should look at making it easier to mix usage of the unified API with lower level APIs.

**Comment by viveksjain** [comment]
Thanks for looking into it! I must confess I don't know the details of the different formats (personally only care about ELF right now), but yes an API providing address(es) and symbol name is precisely the information I need. I'm indifferent to whether it exposes an iterator or something like SymbolMap.

**Comment by philipc** [comment]
Trying to parse PLT entries was too hard, it needed too much architecture specific information, so I gave up on that. #258 implements parsing dynamic relocations for ELF only. Other file formats will never return dynamic relocations, and we'll have to come up with a new API to return their information, but that can be a separate issue.

**Comment by philipc** [comment]
I've confirmed that #258 provides the relocations required for PLT/GOT references ([slightly hacky usage in ddbug](https://github.com/gimli-rs/ddbug/commit/2d4b752b3f0d79f74abf257e4409302a4e19320f)).

**Comment by viveksjain** [comment]
Thanks, that ddbug code is super useful as a reference! Didn't realize this would be so annoying, you actually need to parse assembly from the plt :(

**Comment by philipc** [comment]
The way objdump does it is to hardcode the plt sizes for each architecture, instead of parsing the assembly.

**Comment by viveksjain** [comment]
Interesting, if it's not too much trouble could you provide a pointer to it? Wouldn't it need to parse assembly to figure out the got address being called inside plt, or does it assume got order matches plt order?

**Comment by viveksjain** [comment]
Found https://reverseengineering.stackexchange.com/questions/6213/associating-symbol-names-with-plt-entries, looks like it's relying on order of relocations
