### ISSUE TITLE
Decide how to handle incorrect alignment

### ISSUE THREAD

**Issue by philipc** [gimli-rs/object#230]
See https://github.com/gimli-rs/addr2line/issues/170 for an example of an ELF file with incorrect section header alignment.

We've got a few options for how to handle this:
- Do nothing. Fix your toolchain instead. This option is okay for narrow use cases where we have control of the toolchain, but not suitable for a general purpose library.
- Always handle any alignment. This means that on some architectures we'll generate slower code, which may be undesirable for use cases where we know the alignment is correct.
- Relax the alignment constraints as needed. For the ELF file, we would change `SectionHeader64` to only use types that require 4-byte alignment.
- Add a compile time feature to select whether to support any alignment. This could be done by ensuring that types like `U32` and `U32Bytes` have the same API, and making `U32` an alias of `U32Bytes` when this feature is enabled. I think the only downside is that this prevents supporting both cases in the same application.
- Add a trait parameter to all of the structs so that the application can decide which to support. This is unnecessary complication if one of the other options is good enough.

**Comment by philipc** [comment]
For prior art, `capnp` uses a [feature flag](https://dwrensha.github.io/capnproto-rust/2020/01/19/new-feature-to-allow-unaligned-buffers.html).

**Comment by slonopotamus** [comment]
I believe that `capnp` is used in a much more controlled environments where it is possible to decide at compile time what alignment needs are. But in `object` case, files may come from external sources.

**Comment by philipc** [comment]
While files may come from external sources, they are still generally well formed for the architecture they are intended for. After all, I expect nearly all C code expects the alignment to be correct and reads the headers by directly casting from bytes, and bugs like the one in the PS4 toolchain only go unnoticed because it's for an architecture without alignment constraints.

So I think there are three cases:
1. all files are for a native architecture with alignment constraints
2. all files are for a native architecture with no alignment constraints
3. files may be from a different architecture

If we used the feature flag approach, then it would need to be enabled for uses in cases 2 and 3.
