### ISSUE TITLE
Rustc integration setup

### ISSUE THREAD

**Issue by matprec** [gimli-rs/object#232]
The current rustc integration setup is strictly speaking not conforming with the cargo rule, that [features are additive](https://github.com/rust-lang/cargo/issues/4328). LSP implementations like rust-analyzer assume that crates strictly adhere to that rule and compile/check with `--all-features` by default, which breaks because of the `rustc-dep-of-std` feature. This causes issues like https://github.com/rust-analyzer/rust-analyzer/issues/4702.

I can't think of an elegant solution for this problem, but maybe something along the lines of [explicitly failing](https://internals.rust-lang.org/t/mutually-exclusive-feature-flags/8601/2) with `compile_error!` and a helpful message would make this more discoverable.

**Comment by philipc** [comment]
@alexcrichton Do you have any ideas about what to do for this?

**Comment by philipc** [comment]
#233 is the best I could come up with.

**Comment by alexcrichton** [comment]
Yeah unfortunately I don't know of a great way to solve this. The root of the issue is the weirdness of getting built as part of libstd. I'd love to fix that but I don't really know of another way myself.
