### ISSUE TITLE
Comdat support

### ISSUE THREAD

**Issue by carlokok** [gimli-rs/object#239]
Is threre any chance of support for COMDAT support in Object? 

ELF supports "any" comdat (linker may pick any match)
COFF supports several, (full list https://llvm.org/docs/LangRef.html#comdats )

Essentially this is useful to "bind" things together, if 1 is linked, the other thing is linked too, despite not having a symbol reference or relocation to it.

**Comment by philipc** [comment]
I assume this is for write support to be used in cranelift.

It's definitely something that we should support. I'm not familiar with it though, and can't yet give much advice on what it would involve, but it sounds like we need the ability to define a list of comdat keys in the object, and the ability to set a comdat key for each symbol (or alternatively, define a list of symbols for each comdat key).

**Comment by carlokok** [comment]
Maybe llvms's approach is most flexible:

There's a list of COMDAT's, which has a name and comdat mode (any, exactmatch, largest, noduplicates, samesize)
And a variable / function (Read: section) can optionally refer to it.

ELF then has the restriction that only "any" is supported, and COFF requires the comdat key to match the name of one of the symbols that use it.

**Comment by carlokok** [comment]
So I did some more research:
* https://docs.rs/object/0.20.0/object/enum.SymbolFlags.html << You already have COFF comdat covered.

I'll update this post when I figure out how ELF comdat works.

**Comment by philipc** [comment]
I think we want to provide a unified API for comdat, rather than using the specific file format settings in `SymbolFlags` etc.

I got as far as generating sample COFF and ELF files with comdat sections, but didn't start designing the API yet.

**Comment by philipc** [comment]
It looks like MSVC and GNU differ in how they implement COMDAT. Specifically, GNU doesn't appear to use IMAGE_COMDAT_SELECT_ASSOCIATIVE, and I don't understand yet what they are doing instead. LLVM appears to follow the MSVC method. Do you need to support both of these methods?

**Comment by carlokok** [comment]
I personally need the 'llvm' / msvc method
