### ISSUE TITLE
Plans for macOS Big Sur system libraries in the dyld shared cache?

### ISSUE THREAD

**Issue by mstange** [gimli-rs/object#268]
Hi,

starting with macOS Big Sur, it has become a fair bit harder to obtain symbols from most macOS system libraries, e.g. for profilers or stack traces: The libraries are no longer present as files in the file system, instead they are in a system-wide dyld shared cache file. See [these Google results](https://www.google.com/search?q=big+sur+"dyld+shared+cache") for more information.
So one way to get at the symbols would be to extract the libraries from the cache. Another option, when running inside the process that has the relevant libraries loaded, would be to find the mappings in the process memory and get the symbol table from there.
Do you know if somebody has already started working on rust code to parse the dyld_shared_cache format and write an extractor? Or whether there are any other plans to make getting symbols for macOS system libraries easier in the rust ecosystem?

I imagine this would also be needed to get proper symbols in rust panic stack traces, for example. (Though those seem to be broken at the moment even before Big Sur, see https://github.com/rust-lang/rust/issues/79831 ).

**Comment by philipc** [comment]
> Do you know if somebody has already started working on rust code to parse the dyld_shared_cache format and write an extractor? Or whether there are any other plans to make getting symbols for macOS system libraries easier in the rust ecosystem?

No I don't. If it's something that is needed for backtraces, then it might be appropriate to add parts of the parsing to this crate.

> (Though those seem to be broken at the moment even before Big Sur, see rust-lang/rust#79831

I wasn't aware of that. It might be better to create that issue in the backtrace-rs crate. Sounds like a bad bias calculation somewhere.

**Comment by jrmuizel** [comment]
It would be interesting to check what `lldb` does.

**Comment by philipc** [comment]
From a quick look, lldb gets symbols from the images loaded in memory of the target process, rather than parsing the shared cache itself. It also has the ability to use the images in the host process if the UUID matches, since this is faster. There is some dyld shared cache parsing code, but it is only for iOS. (I've mostly based this on https://reviews.llvm.org/D83023).

**Comment by mstange** [comment]
I've started making an attempt at this in https://github.com/mstange/object/commits/dyld_cache .
