### ISSUE TITLE
section address always 0 when using elf-write

### ISSUE THREAD

**Issue by MathiasKoch** [gimli-rs/object#272]
It seems like the section address will always become 0 when writing ELF files?

Eg using the `objcopy` example:
infile:
```
section              size        addr
.header              1024   134234112
.vector_table         392   134235136
.text              190556   134235528
.rodata             25920   134426084
.data                  48   536870912
.bss                  356   536870960
.uninit             13836   536871320
.ram2               25316   268435456
.defmt                123           0
.debug_loc         453147           0
.debug_abbrev        4619           0
.debug_info       1185116           0
.debug_aranges      10208           0
.debug_ranges      155888           0
.debug_str        2304168           0
.debug_pubnames   1017607           0
.debug_pubtypes    865282           0
.ARM.attributes        56           0
.debug_frame        25936           0
.debug_line        222339           0
.comment              147           0
Total             6502084
```

outfile:
```
section              size   addr
.header              1024      0
.vector_table         392      0
.text              190556      0
.rodata             25920      0
.data                  48      0
.bss                  356      0
.uninit             13836      0
.ram2               25316      0
.defmt                123      0
.debug_loc         453147      0
.debug_abbrev        4619      0
.debug_info       1185116      0
.debug_aranges      10208      0
.debug_ranges      155888      0
.debug_str        2304168      0
.debug_pubnames   1017607      0
.debug_pubtypes    865282      0
.ARM.attributes        56      0
.debug_frame        25936      0
.debug_line        222339      0
.comment              147      0
Total             6502084
```

**Comment by bjorn3** [comment]
As far as I am aware object can only write object files and not executables or shared libraries. Object files don't have section addresses.

**Comment by MathiasKoch** [comment]
Aha.. That would make sense.

In that case i might get some recommendations here. I am looking for a rust crate, that will allow me to read an ELF firmware file (infile above), and replace the data contents of the `.header` section.

Essentially equavalent to `arm-none-eabi-objcopy --update-section ".header=header.bin" infile outfile` but in rust?

**Comment by philipc** [comment]
I'm not aware of any crates that can do that. The ELF write support in this crate might be a useful starting point (you'll need to extend it to handle segments). I would make it specific to ELF though, so don't use the `objcopy` example as a basis.

Other crates that can read/write ELF, but still can't do what you want: goblin (and faerie which uses goblin), elfkit (unmaintained).

**Comment by philipc** [comment]
Added `objcopy` check for supported file type in #352.
Added `write::elf::Writer` and `elfcopy` example in #350. Still no high level support for operations such as `--update-section`.
