### ISSUE TITLE
Does object crate support disassembly of instructions inside the .text section in an object file?

### ISSUE THREAD

**Issue by vaibspider** [gimli-rs/object#273]
Hi,
I am trying to read `.text` section in an object file for instruction disassembly.
I went through the documentation for `object` crate. But, couldn't find such an interface. It seems that `object` crate just hands out the actual raw data of a section in an ELF object file.
Could you please confirm, if this is the case?
Thanks!

**Comment by bjorn3** [comment]
Yes this is correct. Disassembling is something completely different from parsing object files.

**Comment by philipc** [comment]
Correct. Disassembly is not something this crate will ever implement. For disassembly, I've used the rust capstone bindings in the past.

**Comment by vaibspider** [comment]
Ok, thanks! Will try capstone bindings in Rust then.
