### ISSUE TITLE
otool reports "load command 0 filesize field in LC_SEGMENT_64 greater than vmsize field"

### ISSUE THREAD

**Issue by yurydelendik** [gimli-rs/object#286]
This is just to keep my finding on a record.

The llvm-objdump/otool was reporting on one of generated files. The object builder, for macho, used `append_section_data` with alignment == 0x1000. The `address` and `offset` in the `macho_write` quickly got out-of-sync and generated invalid LC_SEGMENT_64 record (see https://github.com/llvm/llvm-project/blob/991df7333d4a6c9904dec17f53b4c531cfb40d49/llvm/lib/Object/MachOObjectFile.cpp#L390 for broken invariant). I removed the alignment to fix the issue, and I did not need it for Macho format.

Recommendation: it will be nice to add asserts from LLVM to quickly find that the object library has an issue with generating valid file (vs tools that consume that).

**Comment by philipc** [comment]
> Recommendation: it will be nice to add asserts from LLVM to quickly find that the object library has an issue with generating valid file (vs tools that consume that).

If you mean during generation, then I doubt many of those asserts are useful. Most are trivially satisfied by the way in which the file is generated. If you mean a new validation tool, then sure, but that's a lot of work.
