### ISSUE TITLE
Add tests for code coverage

### ISSUE THREAD

**Issue by fitzgen** [gimli-rs/object#30]

**Comment by philipc** [comment]
It already does :) It just needs some tests now...

**Comment by fitzgen** [comment]
Heh :-p For some reason I thought it used to have 45% coverage for some reason...

**Comment by luser** [comment]
The code coverage process seems to be broken. From [a recent log](https://travis-ci.org/gimli-rs/object/jobs/421945659):
```
Launching test
ASLR disable failed: EPERM: Operation not permitted
thread 'main' panicked at 'Failed to trace: Sys(EPERM)', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Unexpected signal when starting test
Error when starting test: ECHILD: No child processes
Coverage Results
Tested/Total Lines:
src/elf.rs: 0/184
src/lib.rs: 0/104
src/macho.rs: 0/144
src/pe.rs: 0/100
src/traits.rs: 0/6
src/wasm.rs: 0/109
0.00% coverage, 0/647 lines covered
Sending coverage data to coveralls.io
Coverage data sent
Tarpaulin ran successfully. Failure in tests.
Error during run
```

**Comment by philipc** [comment]
We need to do something like https://github.com/gimli-rs/gimli/pull/334

**Comment by luser** [comment]
Per [the tarpaulin README secton on Travis CI](https://github.com/xd009642/tarpaulin#travis-ci-and-coverage-sites) I think we mostly just need to switch to `sudo: required`. IIRC the Breakpad Travis CI jobs were similarly broken at some point in the past, I think Travis nerfed ptrace.

**Comment by philipc** [comment]
Ah yeah, there's that too.  So there's 3 things to change:

- `sudo: required`
- use crates.io to install tarpaulin
- use nightly rust

and add some tests... which I have given some thought to, but so far I've been too lazy.

**Comment by luser** [comment]
https://github.com/gimli-rs/object/pull/81

**Comment by luser** [comment]
OK, #81 fixes the CI part of it, but it's still 0% coverage without any tests. :)

**Comment by philipc** [comment]
Code coverage is now non-zero (#120).
