### ISSUE TITLE
Data directories

### ISSUE THREAD

**Issue by nickbclifford** [gimli-rs/object#307]
Hi, I'm currently writing a project that deals with .NET PE files, and was trying to use `object` to access CLR metadata, but noticed that the necessary headers are inaccessible. Specifically, I cannot access the CLI header pointer, since it's defined in the PE data directories, which are not publicly exposed.

I noticed that there was some discussion about this in #280.

**Comment by philipc** [comment]
If you're dealing only with PE files, then it might be better to use the lower level APIs ([example](https://github.com/gimli-rs/object/blob/8fbc81e7283c9a075b6805c39ea0d7bcec0372a2/examples/readobj.rs#L4206)). Otherwise we can consider doing something similar to #280.
