### ISSUE TITLE
FileKind cannot be cloned

### ISSUE THREAD

**Issue by mstange** [gimli-rs/object#310]
The `FileKind` enum does not implement Clone. Is this intentional? Seems like it could even be Copy.

https://github.com/gimli-rs/object/blame/ad3a1ad4cd1d2521578ab9092dae4929ea1288fc/src/read/mod.rs#L120

**Comment by philipc** [comment]
Definitely not intentional. It should be similar to other enums.

**Comment by philipc** [comment]
I want to do another `object` release relatively soon. Are you still doing development that might require more changes?

**Comment by mstange** [comment]
I'm eagerly anticipating a release. I am doing more development but there's nothing currently blocking me, and I definitely don't want to hold up the release. Thanks!
