### ISSUE TITLE
Implement dynsym

### ISSUE THREAD

**Issue by oberien** [gimli-rs/object#33]
[Both ELF and MachO (can) have dynamic symbols](http://timetobleed.com/dynamic-symbol-table-duel-elf-vs-mach-o-round-2/) (I don't know if PE has something similar). Would it be possible to implement a function `dynamic_symbols` in addition to `symbols`?

For now I have only looked at the ELF code, so my suggestions are based on that.
If there are dynamic symbols in PEs, we could simply add such a function to the `Object` trait.
If that's not the case, I'd suggest the following approaches:

1. Append all dynamic symbols to the result returned by `symbols`.
1. Make `dynamic_symbols` a function of trait `Object` returning `Vec<Symbol<'a>>`. Implement it for ELF and MachO and make it return an empty vec for PE. This behaviour suggests that it's possible to have dynamic symbols in PEs.
1. Like the former, but panic if it's called on PE. While this makes the contract stricter, it should be the better behaviour, implying that this is not possible for PEs.
1. Like the former, but make `dynamic_symbols` return `Option<Vec<Symbol<'a>>` and return `Some(vec)` for ELF and MachO and `None` for PE. I think that this approach just complicates things.
1. Add the `dynamic_symbols` function to both ELF and MachO and let the user create the respective struct himself instead of creating a `File`.
1. Like the former, but make `inner` of `File` public (or expose it somehow) so that it's possible for the user to instantiate a `File` but still call `dynamic_symbols`.

For ELF files I was able to just exchange `symtab` and `strtab` with `dynsym` and `dynstrtab` respectively and it worked as expected. Therefore I'd suggest making the current `symbols` function private, but add 2 parameters for the symbol table and the string table, which the new `symbols` and `dynamic_symbols` call.
I did this with testwise (and because I need it) for `ElfFile` in 3ae266f861129df4a610bbc067956314783b2f3e .

**Comment by philipc** [comment]
PE has imports/exports at least, which I think serve the same purpose.

Can you elaborate what you want to use this for? I was intending to avoid duplicating the existing `symbols` API for dynamic symbols. It exists only because we need to calculate sizes for Mach-O. Instead I wanted to added iterators for both local symbols and dynamic symbols. Will that meet your needs?

**Comment by oberien** [comment]
Iterators are fine with me. 

I inject a library into a binary with `LD_PRELOAD` and want to hook the binary's functions. I'd like to get their addresses from the dynsym section.

**Comment by philipc** [comment]
Fixed in #37
