### ISSUE TITLE
Look into how mingw produces DWARF-in-PE

### ISSUE THREAD

**Issue by luser** [gimli-rs/object#40]
The mingw toolchain produces PE binaries with DWARF in them. I'm not 100% sure how it works, but it should be possible to support with gimli+object. This is a follow-on from https://github.com/gimli-rs/object/pull/39 .

**Comment by luser** [comment]
@jon-turney has submitted patches to Breakpad to support this use case, maybe he can point us at some resources that explain what mingw does.

**Comment by luser** [comment]
Specifically, there's this patchset that adds support for dumping symbol information from mingw PE files: https://codereview.chromium.org/1451693003/

**Comment by jon-turney** [comment]
> @jon-turney has submitted patches to Breakpad to support this use case, maybe he can point us at some resources that explain what mingw does.

I'm not sure there's much to explain.  The same DWARF information sections are present, but the container is PECOFF rather than ELF.

**Comment by philipc** [comment]
Fixed in #69
