### ISSUE TITLE
write/elf: Allow disabling unique names for subsection

### ISSUE THREAD

**Issue by bjorn3** [gimli-rs/object#409]
Currently object writes elf files with section names like `.text.foo` and `.text.bar` for the `foo` and `bar` sections. Elf allows naming both sections `.text`. This can save a lot of space on section name strings.

An api I could imagine would be to use `.text` as section name if the base section name is `.text` and the subsection name is empty. Currently this would result in the name `.text.` and panic if there are multiple subsections for the same section due to the same section name being inserted into a `StringTable` more than once.

**Comment by philipc** [comment]
Should this apply to COFF too? Mach-O will be fine because the name is ignored anyway.

**Comment by philipc** [comment]
> panic if there are multiple subsections for the same section due to the same section name being inserted into a StringTable more than once.

Can you elaborate? I don't see where this would happen.

**Comment by bjorn3** [comment]
I just tried using a single name for all subsections in Cranelift: https://github.com/bytecodealliance/wasmtime/pull/9742 There is indeed no panic. It does still produce section names like `.text.` when giving an empty name as input.
