### ISSUE TITLE
COFF flags interpreted differently from ELF/MachO flags

### ISSUE THREAD

**Issue by nikic** [gimli-rs/object#411]
When ELF or MachO flags are explicitly specified, they override the default flags implied by the SectionKind, see https://github.com/gimli-rs/object/blob/e45a3d12d75b3eed99e7183d3035803bfdd15b0d/src/write/elf/object.rs#L689 and https://github.com/gimli-rs/object/blob/e45a3d12d75b3eed99e7183d3035803bfdd15b0d/src/write/macho.rs#L393.

However, for COFF the SectionKind flags are applied unconditionally in https://github.com/gimli-rs/object/blob/e45a3d12d75b3eed99e7183d3035803bfdd15b0d/src/write/coff.rs#L310. The specified characteristics are only added, they don't replace the defaults. It makes sense to me that the other flags (e.g. relating to alignment) are always added, but I'd have expected that the flags implied by SectionKind are omitted in this case, for consistency with ELF/MachO.

**Comment by philipc** [comment]
Thanks for the report. I agree this should be changed, and I'll do a PR for it. Is this causing problems for an existing usage of this crate?

**Comment by nikic** [comment]
I noticed this in the context of https://github.com/rust-lang/rust/pull/92029, though TBH I'm not sure which flags COFF should actually use there, possibly the ones implied by SectionKind::Debug would be fine. The desire is to have a section that is retained in the linked artifact (a shared object) without being loaded into memory.
