### ISSUE TITLE
Ways to store parsed File(s) in Vec<File> with its external data?

### ISSUE THREAD

**Issue by DarkoreXOR** [gimli-rs/object#413]
I'm trying to write a linker and I'm having a problem storing lots of parsed object files. Right now I need multiple passes and have to parse each file over and over again, which isn't very efficient. How to store the parsed files in vec or other structures, separated from its data, which should also be stored somewhere? Because of the reference to external data, I can't think of anything. All your examples use a single object file. It would be better if some reader is passed to the parser, not by reference. What solutions do I have?

**Comment by bjorn3** [comment]
Can you keep all files mapped in memory? Then you can simply keep each parsed `File`.

**Comment by mstange** [comment]
The trouble is keeping the mapped memory alive, and convincing the compiler that the Vec keeps the mapping alive for the File's life time. This is a bit tricky in Rust.

In the past, I've used [`elsa::vec::FrozenVec`](https://docs.rs/elsa/latest/elsa/vec/struct.FrozenVec.html) for this. It's an append-only Vec which gives you references to its members with the lifetime of the Vec. You just need to host the FrozenVec somewhere "outside" the Vec of Files.

**Comment by DarkoreXOR** [comment]
Great, [`elsa::vec::FrozenVec`](https://docs.rs/elsa/latest/elsa/vec/struct.FrozenVec.html) helped me, thanks for the help.

But I'd still like to have a slightly different design, something like "dependency injection" right into the `File::parse(...)` **(by value)**, with our data read implementation. So that it would end up being without references and lifetimes outside, so that we could do without additional crates, unsafe code, and with the ability to store the parsed files inside the structure.

P.S. I've seen ReadRef, but it's used via reference and requires a Copy trait, which collections can't have.

**Comment by philipc** [comment]
Use of references isn't going to change, sorry. Instead of storing `File`, you should store the parsed information that you need.
