### ISSUE TITLE
How to access maxprot ?

### ISSUE THREAD

**Issue by everettjf** [gimli-rs/object#414]
```
    let macho = object::read::macho::MachOFile64::<object::endian::LittleEndian>::parse(&*mmap).unwrap();
    for segment in macho.segments() {
        println!("{}", segment.maxprot()); // how to access maxprot ?
    }
```
How to access maxprot ?

```
#[derive(Debug)]
pub struct MachOSegment<'data, 'file, Mach, R = &'data [u8]>
where
    'data: 'file,
    Mach: MachHeader,
    R: ReadRef<'data>,
{
    file: &'file MachOFile<'data, Mach, R>,
    internal: &'file MachOSegmentInternal<'data, Mach, R>,
}
```

I found maxprot in segment in  `internal`.

```
#[derive(Debug, Clone, Copy)]
pub(super) struct MachOSegmentInternal<'data, Mach: MachHeader, R: ReadRef<'data>> {
    pub data: R,
    pub segment: &'data Mach::Segment,
}
```

So , how could I access maxprot ? Should I add functions for ObjectSegment ?

Thanks :)

**Comment by philipc** [comment]
For an example using the lower level API, see https://github.com/gimli-rs/object/blob/56299a3b6acb4d38fc14e0a2557112433f82e789/crates/examples/src/readobj/macho.rs#L541

I'm not sure that maxprot makes sense to access in the unified API. What would the equivalent be for ELF and PE/COFF?

**Comment by everettjf** [comment]
Thanks. 
I originally want to access R,W,E attribute for the load command.

For example,  ELF PT_LOAD exists p_flags.
![image](https://user-images.githubusercontent.com/1665109/147533043-7858c447-dbf0-43dc-a276-ed97b9956a83.png)

PE/COFF exists a  Characteristics (section flags)
https://docs.microsoft.com/en-us/windows/win32/debug/pe-format#section-flags

**Comment by philipc** [comment]
We could certainly add a RWX flags function to `ObjectSegment`, but probably it should use `initprot` for Mach-O? I'm not sure.

What do you want to achieve by reading `maxprot`?

**Comment by everettjf** [comment]
Oh, I get it. The `initprot` is what I really need. I just use `maxprot` as an example.

It's great if RWX flags  could be added.

**Comment by everettjf** [comment]
Are you writing this new flag function ? Otherwise I think I could make a pull request. @philipc

**Comment by philipc** [comment]
I won't get to it immediately. Feel free to make a pull request.
