### ISSUE TITLE
read/pe: Support exception tables parsing

### ISSUE THREAD

**Issue by a1phyr** [gimli-rs/object#434]
It would be a great feature to have !

For the record, `goblin` already supports it: https://github.com/jan-auer/goblin/blob/master/src/pe/exception.rs

**Comment by mstange** [comment]
If new parsing code for this format were to be written, I'd prefer to have it in a separate crate, similar to [`macho-unwind-info`](https://github.com/mstange/macho-unwind-info). Then I'd be able to use it in [`framehop`](https://github.com/mstange/framehop) without having to take object as a dependency.

**Comment by philipc** [comment]
It looks like this now exists at https://github.com/afranchuk/pe-unwind-info. Reopen if that isn't sufficient.
