### ISSUE TITLE
Data of the .bss segment

### ISSUE THREAD

**Issue by kriskwiatkowski** [gimli-rs/object#440]
I use ``object::read::File`` to read ELF64 on Intel. It can read content of any segment except for the ``.bss`` segment. Namely, I do this:

```
        let section = match self.bin.section_by_name(sec) {
            Some(section) => section,
            None => return Err(ErrCode::ErrorSectionNotFound)
        };

        println!("Section size: {}", section.size());
        match &section.data() {
            Ok(tmp) => {
                /// Don't print more than 8 characters
                let print_len = if tmp.len() > 8 { 8 } else {tmp.len()};
                println!("Section data: len={} content={:?}", tmp.len(), &tmp[0..print_len]);
            }
            Err(_) => return Err(ErrCode::ErrorProcessing)
        };
```
When using it to parse different segments in the ``/bin/ls`` binary, I get:
```
Section size: 75730
Section data: len=75730 content=[232, 171, 249, 255, 255, 232, 166, 249]
Section size: 21065
Section data: len=21065 content=[1, 0, 2, 0, 0, 0, 0, 0]
Section size: 4824
Section data: len=0 content=[]
```
So, the section size of ``.bss`` is correct, but ``section.data()`` gives no data. I know the ``.bss`` is full of zeros, so maybe that's by design.

Nevertheless, in my program, I calculate cryptographic hash of all sections. I would prefer to have generic code that handles all sections in a same way. But now I  would need to handle ``.bss`` differently, as I can't get its content.

**Comment by philipc** [comment]
This is by design. It's not possible to return the `.bss` data because it doesn't exist in the file.

**Comment by kriskwiatkowski** [comment]
Hmmm... after thinking about it for a few minutes. Indeed, it works OK. Library should return contents of the data stored in the binary.
It works perfectly! Thanks
