### ISSUE TITLE
Modify existing elf?

### ISSUE THREAD

**Issue by MabezDev** [gimli-rs/object#446]
I'd like to read an existing elf, change some things, add new sections etc. I can't seem to find a way to create an ELF writer from an existing elf file?

I saw the `elfcopy` example, but the heavy lifting function seems quite large: https://github.com/gimli-rs/object/blob/0a38064531fef4ddbaf93770a3551d333338980e/crates/examples/src/bin/elfcopy.rs#L83 is there a simpler API, or a better way to achieve this?

**Comment by philipc** [comment]
Nothing exists for this yet. There has been a desire for this sort of thing in the past (#148) but no one has done the work yet, and I don't have time currently.

**Comment by philipc** [comment]
Implemented in #618
