### ISSUE TITLE
Handle compressed ELF sections

### ISSUE THREAD

**Issue by rocallahan** [gimli-rs/object#47]
For gimli's `dwarfdump` to handle compressed ELF sections, support should be added to `object`.

**Comment by rocallahan** [comment]
Actually I guess support needs to be added to both `goblin` and `object`.

**Comment by rocallahan** [comment]
I suppose we could just handle it in `object`.

Would you accept addding a method `ObjectSection::uncompressed_data` that returns `Cow<'data, [u8]>`? Perhaps also `Object::uncompressed_section_data_by_name`?

**Comment by rocallahan** [comment]
And we'd have to add a `flate2` dependency.

**Comment by fitzgen** [comment]
SGTM!

**Comment by philipc** [comment]
Would `Object::uncompressed_section_data_by_name` automatically load `.zdebug_info` if `.debug_info` is requested?

**Comment by rocallahan** [comment]
> Would Object::uncompressed_section_data_by_name automatically load .zdebug_info if .debug_info is requested?

Note that libbfd will look for `.debug_info` first and fall back to `.zdebug_info` if that's not found, independent of the setting of the compression flag.

It would probably make more sense to define yet another function, say `uncompressed_debug_section_data`, that does the magical .zdebug fallback and "ZLIB" decompression.

**Comment by philipc** [comment]
> Is that what you want?

I'm happy with anything that works, but we need to do the fallback somewhere, and currently gimli consumers only look for the single name provided by `Section::section_name`. So doing it here would mean no changes needed in gimli.

> What about doing that for all .debug_* sections?

Yes it would have to be all sections.

> Would it be OK with you if it also automatically decompressed debug sections starting with "ZLIB" like libbfd does?

Yes.

> It would probably make more sense to define yet another function, say `uncompressed_debug_section_data,` that does the magical .zdebug fallback and "ZLIB" decompression.

Do you mean `Object::uncompressed_debug_section_data`?

I'd rather we only add separate methods if we think there's going to be use cases that require them. So I'd actually be okay with changing `Object::section_data_by_name` to do all the magic and return `Cow<'data, [u8]>`, unless you think there's a reason not to.

**Comment by philipc** [comment]
That makes it sound like we shouldn't decompress sections simply because they start with ZLIB then. So I think `Object::section_data_by_name` should do the following:
- look up the section with the given name
- if it exists and has the SHF_COMPRESSED flag, then decompress it
- otherwise if the section name starts with `.debug_`, then look up the `.zdebug_` section, verify it starts with ZLIB, and then decompress it

**Comment by rocallahan** [comment]
OK I've implemented this. First we need to add support for ELF Chdrs to `goblin`: https://github.com/m4b/goblin/pull/83

**Comment by philipc** [comment]
I'm fine with temporarily changing Cargo.toml to specify a git version.

**Comment by rocallahan** [comment]
I'm not in a hurry with this so I guess it's less churn to wait for the `goblin` release.

**Comment by philipc** [comment]
FYI, goblin 0.0.15 has been released.

**Comment by philipc** [comment]
Fixed by #50
