### ISSUE TITLE
write/coff: Merge all .rdata$.refptr. sections

### ISSUE THREAD

**Issue by bjorn3** [gimli-rs/object#474]
It seems that in https://github.com/bjorn3/rustc_codegen_cranelift/issues/1249#issuecomment-1272290580 the windows linker spends most of the time (almost 75%) churning through the names of all these sections.

**Comment by philipc** [comment]
I think the current behaviour is copying what mingw does. Can you give me an example object file generated by the llvm backend?

**Comment by afonso360** [comment]
I took a random lib (`libbevy_ecs`) that appears in the dependencies of `bevy` and here's what I got.

[`objdump -h libbevy_ecs_llvm.rlib`](https://gist.github.com/afonso360/437a6728ec4f6d1761ced1e408ad70d9)

[`llvm-objdump -h libbevy_ecs_cgclif.rlib`](https://gist.github.com/afonso360/be2a52013f4aa7da247009419a174b42)

We print fewer sections 2497 vs llvm which spits out 30376. However, llvm produces them all with the same name, so I wonder if MSVC is able to deal with that better and possibly merge them all before processing somehow.

Here's a [link](https://github.com/afonso360/bevylibs) to a repo with both libraries, github does now allow me to attach them to this comment.

Its worth noting that I only see this behaviour with MSVC's `link.exe`, if i try to link with `rust-lld.exe` everything works as normal, so it really appears to be a MSVC only issue.

I'm going to try to minimize our section names and see if the issue goes away.

**Comment by afonso360** [comment]
Yep, that seems to have done the trick! I applied this [commit](https://github.com/afonso360/object/commit/7361e2cbce5ba05b1d60c44e3a4fe31c425e21fe) to duplicate all our section names and it now links in a reasonable time.

Would you like me to open a PR for that, or should we deal with this in a different manner?

**Comment by philipc** [comment]
llvm isn't emitting refptr symbols at all in that library. The reason it has a large number of sections is because llvm is using a separate section for each function and data symbol, while cgclif has a single section for each of `.text`, `.rdata`, and `.data`.

I don't want to apply a commit without first having a complete understanding:
- Is there any way to get llvm to emit refptr symbols, and if so, what sections does it create then?
- Does cgclif really need to emit refptr symbols, or should we provide a way for cgclif to avoid emitting them?
- If we duplicate section names, does it matter what they are called? Is there a reason you chose `.rdata$.refptr`?

**Comment by afonso360** [comment]
I don't really know how to answer the first two questions, but maybe @bjorn3 can help?

> If we duplicate section names, does it matter what they are called? Is there a reason you chose `.rdata$.refptr`?

Not really, I just [tried with `.thisisatest`](https://github.com/gimli-rs/object/commit/f2669defd59ad33bdfe9b05662126f7255a8e84f) and it also works all right. I chose `.rdata$.refptr` because it was what was there before (without the trailing `.`).

**Comment by bjorn3** [comment]
> The reason it has a large number of sections is because llvm is using a separate section for each function and data symbol

AFAIK rustc disables `-ffunction-section` on Windows to avoid hitting the section count limit of COFF.

> Does cgclif really need to emit refptr symbols, or should we provide a way for cgclif to avoid emitting them?

When is_pic is enabled, Cranelift emits GotRelative relocations when accessing data. Object lowers this to .rdata$.refptr.* for COFF object files. Without is_pic enabled it isn't possible to link the object files into dylibs afaik and we don't know in advance if a crate will end up being linked into an executable or a dylib.

**Comment by philipc** [comment]
> AFAIK rustc disables -ffunction-section on Windows to avoid hitting the section count limit of COFF.

Why does `libbevy_ecs_llvm.rlib` have a lot of `.text` sections then?

> When is_pic is enabled, Cranelift emits GotRelative relocations when accessing data. Object lowers this to .rdata$.refptr.* for COFF object files. Without is_pic enabled it isn't possible to link the object files into dylibs afaik and we don't know in advance if a crate will end up being linked into an executable or a dylib.

`libbevy_ecs_llvm.rlib` doesn't have these refptr stubs. Is there a difference in what knowledge is available to llvm versus cranelift?

**Comment by bjorn3** [comment]
> Why does libbevy_ecs_llvm.rlib have a lot of .text sections then?

Just checked the rustc source and it seems it is only disabled on MinGW. Based on some discussion I found elsewhere it seems that MSVC and MinGW both have a trick now to avoid the section limit using COMDAT, but both in incompatible ways. It is still disabled on MinGW due to a binutils bug.

> libbevy_ecs_llvm.rlib doesn't have these refptr stubs. Is there a difference in what knowledge is available to llvm versus cranelift?

I think there is some difference in how PE and ELF implement dylibs that Cranelift doesn't know about. I'm not familiar enough with PE to tell what though.

**Comment by philipc** [comment]
Based on https://learn.microsoft.com/en-us/windows/win32/debug/pe-format#grouped-sections-object-only, I think it is okay to rename the sections to `.rdata$.refptr`, so please create a PR with that change. I still think that Cranelift is using `GotRelative` more than it should, but that is outside the scope of this crate.
