### ISSUE TITLE
ELF: unified write API doesn't generate program headers

### ISSUE THREAD

**Issue by athre0z** [gimli-rs/object#478]
The unified write API currently doesn't offer the ability to generate program headers. It is my understanding that program headers are a strict requirement for ELF binaries to actually be loadable, so I'm wondering whether I'm missing something here? Is the unified write API an unfinished feature? I noticed that it also doesn't offer the ability to set the entry point.

**Comment by philipc** [comment]
The unified write API is only for object files, not executable files.

**Comment by athre0z** [comment]
Ah -- I see, thanks for the quick response! It might make sense to make that a bit more explicit on the main overview page. It currently says:

> [write::Object](https://docs.rs/object/0.29.0/object/write/struct.Object.html) allows building a COFF/ELF/Mach-O object and then writing it out.

Which, I guess, is accurate. However, in my head, an executable is kind of a special case of an object file, so this didn't really communicate to me that it can't generate executables.

**Comment by philipc** [comment]
Yes, that's true, and it probably doesn't help that `read::Object` does support executables.

Also, maybe a more helpful answer is that a unified write API for executables would be hard to design, and not very unified: there would be lots of file format specific settings required.

What's your use case for writing executables? Normally that's a linker's job, and experience has shown that linkers are too performance sensitive for a unified API to be workable. The other use case I've seen is for modifying executable files and again I don't think a unified API will work well due to the need to preserve all possible file format features (rather than providing an API that supports only a common subset of the file format features).

**Comment by athre0z** [comment]
> Also, maybe a more helpful answer is that a unified write API for executables would be hard to design, and not very unified: there would be lots of file format specific settings required.

Yes, that does make sense. I see how this would be hard to do well.

> What's your use case for writing executables? 

I don't really have one myself. We're building [a universal profiler](https://www.elastic.co/observability/ebpf-continuous-code-profiling) for all sorts of native, interpreted and JITed runtimes at Elastic and I was investigating stack unwinding for the wasmtime/cranelift environment. The wasmtime people use the unified write API as a serialization format for their generated code when the [`Engine::precompile_module`](https://docs.wasmtime.dev/api/wasmtime/struct.Engine.html#method.precompile_module) / [`Module::deserialize_file`](https://docs.wasmtime.dev/api/wasmtime/struct.Module.html#method.deserialize_file) methods are used and then manually map the ELF file into memory with `mmap` calls. This kind of turns their binary into a hybrid between an executable and an object file. 

I originally assumed that their intention was to build a proper executable file and that they might be doing the manual `mmap`ing (instead of `dlopen`ing) for consistency with their full JIT mode that just allocates RWX memory. The lack of program headers in memory confuses a lot of our tooling (as well as existing tools like GDB, e.g. when inspecting their process in a coredump), so I figured they might have simply forgotten to emit the program headers by accident.

In any case, this is definitely not an issue of this library, so I'll take this to the wasmtime repository instead. :-) Shall we close this here or do we leave it open as a reminder for improvements in the documentation?

**Comment by mstange** [comment]
> The lack of program headers in memory confuses a lot of our tooling (as well as existing tools like GDB, e.g. when inspecting their process in a coredump), so I figured they might have simply forgotten to emit the program headers by accident.

According to [this wasmtime documentation](https://docs.wasmtime.dev/examples-profiling-perf.html), you can ask wasmtime to emit a [jitdump](https://github.com/torvalds/linux/blob/master/tools/perf/Documentation/jitdump-specification.txt) file which describes these "hybrid" images.

**Comment by athre0z** [comment]
> According to [this wasmtime documentation](https://docs.wasmtime.dev/examples-profiling-perf.html), you can ask wasmtime to emit a [jitdump](https://github.com/torvalds/linux/blob/master/tools/perf/Documentation/jitdump-specification.txt) file which describes these "hybrid" images.

Thanks for the links! There are multiple issues with jitdump that -- IMHO -- prevent it from being useful for production profiling. From the top of my head:

- Users must explicitly enable its generation both via compile-time features and a runtime-flag before profiling can begin
- The profiler must be started before the runtime
- No well-defined support for inline function symbolization exists

All of these aren't unreasonable if the goal is profiling an example on a local machine, but they come major problems when the intention is to profile everything across large fleets of servers.

For a runtime like wasmtime that JITs on per-module basis, my personal preference would be for them to just emit regular ELF executables with DWARF + .eh_frame, allowing profilers to treat them like native code. For example, the wasmer runtime allows doing that when [`wasmer_engine_dylib`](https://docs.rs/wasmer-engine-dylib/latest/wasmer_engine_dylib/) is used. 

`wasmtime` isn't actually all that far away from having that as well: they are already generating ELF object files and `.eh_frame` sections; they just lacking the program headers. This is not at all a hard problem to work around by special-casing their processes, but in the interest of everyone writing profilers, generating a regular executable would simplify things.

**Comment by mstange** [comment]
>     * Users must explicitly enable its generation both via compile-time features and a runtime-flag before profiling can begin

Yes, that is a problem.

>     * The profiler must be started before the runtime

Oh, why is that?

>     * No well-defined support for inline function symbolization exists

Yes, ugh. This seems like a really big oversight, and I was very disappointed about it when I first learned about the jitdump format.

> For a runtime like wasmtime that JITs on per-module basis, my personal preference would be for them to just emit regular ELF executables with DWARF + .eh_frame, allowing profilers to treat them like native code. For example, the wasmer runtime allows doing that when [`wasmer_engine_dylib`](https://docs.rs/wasmer-engine-dylib/latest/wasmer_engine_dylib/) is used.

Interesting!

**Comment by athre0z** [comment]
> > * The profiler must be started before the runtime
> 
> Oh, why is that?

I'm not sure, but it was cited as a limitation in the [corresponding patch-series](https://lwn.net/Articles/638566/):

> The current support only works when the runtime is monitored from start to finish

It's possible that this limitation only applies to the HotSpot support or was since lifted.

**Comment by bjorn3** [comment]
Wasmtime knows how to generate program headers by patching the object file created using the unified write API, but it only does so for the gdbjit integration: https://github.com/bytecodealliance/wasmtime/blob/f082756643ca4e10ab9184a623e38565e7dabe21/crates/jit/src/debug.rs#L118-L165

**Comment by bjorn3** [comment]
cc @alexcrichton

**Comment by bjorn3** [comment]
By the way wasmtime doesn't use helpful symbol names. Instead you get _wasm_function_4 or _trampoline_7. It does translate dwarf debuginfo if you pass `-g` when compiling though. Be aware that there is a bug in this code causing crashes in some cases.
