### ISSUE TITLE
read/coff: Support reading coff bigobj files

### ISSUE THREAD

**Issue by bjorn3** [gimli-rs/object#489]
When `/bigobj` is passed to the compiler on windows, an extension of the coff object file format is used with support for more than 64k sections. I couldn't quickly find a description of the format and the file command doesn't recognize files in this format, but LLVM does support it.

**Comment by philipc** [comment]
In addition to LLVM source, there's some info at https://developercommunity.visualstudio.com/t/pecoff-format-specification-issues/408610

See also #154, although I think that is a different file format again.

**Comment by bjorn3** [comment]
Yeah, #154 seems to be about MSVC LTO object files. Those start with the same 00 00 FF FF header according to LLVM.

**Comment by assarbad** [comment]
I am not sure #154 is necessarily about the same as `/bigobj`. It could be, though, since `ANON_OBJECT_HEADER`, `ANON_OBJECT_HEADER_V2`, `ANON_OBJECT_HEADER_BIGOBJ` **and** `IMPORT_OBJECT_HEADER` all use the same marker: `IMAGE_FILE_MACHINE_UNKNOWN` (== 0) for the first and 0xFFFF for the second.
