### ISSUE TITLE
No access to `r_offset` in a relocation entry with unified read API?

### ISSUE THREAD

**Issue by Acciente717** [gimli-rs/object#490]
Hi there. I'm trying to access the `r_offset` field in the relocation entries, but I found no method providing that access.

I'm working with ELF format. I was wondering if `r_offset` is very specific to ELF so it doesn't make sense to include it into the unified API. If it's the case, what's the best alternative way to access the `r_offset` field?

Thank you very much for your help.

**Comment by bjorn3** [comment]
The `file.dynamic_relocations()` method returns an iterator whose items are a pair of the location the relocation applies to (`r_offset` in the case of ELF files) and a `Relocation` containing the relocation data excluding the offset. I think you were looking at `Relocation`.

**Comment by Acciente717** [comment]
Oh my goodness. Thank you for your enlightenment. Don't know why I was neglecting the `.0` field returned from `SectionRelocationIterator`.
