### ISSUE TITLE
CoffSymbol cant access underlying ImageSymbol field

### ISSUE THREAD

**Issue by invlpg** [gimli-rs/object#493]
Hi id like to get access to the storage_type and derived_id fields of the ImageSymbol structure when it is encapsulated into CoffSymbol... Seems you only have wrapper methods that return some higher level information. 

Maybe I am missing something, can i convert a CoffSymbol into a ImageSymbol?

Thanks.

References:
https://docs.rs/object/latest/object/read/coff/struct.CoffSymbol.html (CoffSymbol)
https://docs.rs/object/0.30.0/src/object/read/coff/symbol.rs.html#325 (id like access to this field)
https://docs.rs/object/0.30.0/src/object/pe.rs.html#791 (and this field)

Possible Solution:
https://docs.rs/object/latest/object/read/trait.ObjectSymbol.html#provided-methods

Add another provided method that returns the underlying symbol (clone it)...

`fn native_symbol(&self) -> NativeSymbolType` where you can do `type NativeSymbolType` and whomever impliments ObjectSymbol needs to set the NativeSymbolType (for example ImageSymbol for coff).

**Comment by philipc** [comment]
My strong opinion is that if you care about such file format specific details, then you should be using the low level API, not the format independent unified API. For example: https://github.com/gimli-rs/object/blob/0941701f1222d0946791868b7b13385f54cf1d4a/crates/examples/src/readobj/pe.rs#L569-L571

However, I can't stop people from doing otherwise, and in the past we have added methods to do this, such as [`PeFile::nt_headers`](https://docs.rs/object/latest/object/read/pe/struct.PeFile.html#method.nt_headers). So we could add a method to `CoffSymbol`.

Note that we wouldn't add another method to `ObjectSymbol`, because without having a common trait for `NativeSymbolType` it would be impossible to have generic code that uses it, and if the code isn't generic then you already know that it is `CoffSymbol` so you can use any method on it.

**Comment by invlpg** [comment]
https://github.com/gimli-rs/object/pull/494/commits/aac8c9b47bc15f4e93cae038cecd13a3818b50e8

**Comment by invlpg** [comment]
> 

 I am new to rust but I assume you could get around the generic base class issue with `native_symbol` by using an Option? where we return None if the symbol has no underlying native symbol type

**Comment by invlpg** [comment]
> My strong opinion is that if you care about such file format specific details, then you should be using the low level API, not the format independent unified API. For example:
> 
> https://github.com/gimli-rs/object/blob/0941701f1222d0946791868b7b13385f54cf1d4a/crates/examples/src/readobj/pe.rs#L569-L571
> 
> However, I can't stop people from doing otherwise, and in the past we have added methods to do this, such as [`PeFile::nt_headers`](https://docs.rs/object/latest/object/read/pe/struct.PeFile.html#method.nt_headers). So we could add a method to `CoffSymbol`.
> 
> Note that we wouldn't add another method to `ObjectSymbol`, because without having a common trait for `NativeSymbolType` it would be impossible to have generic code that uses it, and if the code isn't generic then you already know that it is `CoffSymbol` so you can use any method on it.

I am new to rust but I assume you could get around the generic base class issue with native_symbol by using an Option? where we return None if the symbol has no underlying native symbol type.

Anyways heres a pull rq for this issue: https://github.com/gimli-rs/object/pull/494

**Comment by philipc** [comment]
How you would call this code? For example:
```rust
fn use_symbol<S: ObjectSymbol>(symbol: &S) {
    let native = symbol.native_symbol();
    // What code would you write here? You know nothing about the type of native.
}
```

In comparison, if you know that the type is `CoffSymbol`, then you can use any method on `CoffSymbol` without needing to add it to `ObjectSymbol`. For example, if you added `CoffSymbol::raw_symbol` then you can do this:
```rust
fn use_symbol(symbol: &CoffSymbol) {
    let native = symbol.raw_symbol();
    println!("{:?}", native);
}
```


I see your PR, but have you written and tested code that uses that PR?

**Comment by invlpg** [comment]
I think your `CoffSymbol::raw_symbol` idea is actually better in this situation since I dont want to mess with anything outside of the scope of coff files atm. No i havent tested the code either. I'll revert to master and implement raw_symbol for CoffSymbol.

**Comment by philipc** [comment]
If you don't want to mess with anything outside of coff files, then why not use the low level API?

**Comment by invlpg** [comment]
From my understanding to get a `ImageSymbol` you need to parse a `pe::SymbolTable` which requires parsing a `ImageFileHeader`. 

All this parsing is already done behind the scenes by the higher level wrapper code. Addtionally it would be messy to reparse all of this just for me to get derived_id and storage_class....?

**Comment by philipc** [comment]
Yes, adding `raw_symbol` is good. I just wanted an understanding of your perspective.

**Comment by invlpg** [comment]
Ok i went ahead and removed my original changes, added the `raw_symbol` function. 

I went ahead and added a test case for the code too...

Ready to merge.
