### ISSUE TITLE
CoffSymbol::section returns "invalid" section index 

### ISSUE THREAD

**Issue by invlpg** [gimli-rs/object#495]
Hello again, coff symbols contain a field called "section_index" which is actually not zero based.

So for example if you try something like this:

```rust
let section_idx = sym.section_index().unwrap();
let section = coff.section_by_index(section_idx);
```

You will be getting the incorrect section. 

References:
https://learn.microsoft.com/en-us/windows/win32/debug/pe-format#coff-symbol-table
![image](https://user-images.githubusercontent.com/75157064/210013595-e9bf7f77-e56b-47a0-9ba1-76bdfce5ac7a.png)

Effected code:
https://github.com/gimli-rs/object/blob/0941701f1222d0946791868b7b13385f54cf1d4a/src/read/coff/symbol.rs#L429-L451

Its subjectable if you want to view this as invalid, but i think if you are going to write wrapper code around the symbol you should try and return a section index that is zero based since the other CoffFile code uses zero based numbers for section index.

quick and easy fix you want me to do it.

**Comment by invlpg** [comment]
Changing the return value could break existing code, so maybe you could make a new function that returns the zero_based_section_index?

**Comment by invlpg** [comment]
Nvm seems section_by_index is one based as well..? No issue here but i suspect there is going to be an issue elsewhere with this.

**Comment by philipc** [comment]
Using a 1 based index was a deliberate design choice. In my opinion it's less error prone to use indices that match the convention used by the file format.
