### ISSUE TITLE
read/elf: Make it easier to parse ELF notes from /sys/kernel/notes

### ISSUE THREAD

**Issue by mstange** [gimli-rs/object#511]
Here's some code which reads the kernel's ELF build ID by parsing `/sys/kernel/notes`: https://github.com/mstange/samply/blob/1d71084e3054a9d2b6bd9a399cfcd659f937f613/samply/src/linux_shared/kernel_symbols.rs#L34-L38

I had to copy the `NoteIterator` code into this file because IIRC there was no public API to construct it.

*Edit: fixed link*

**Comment by philipc** [comment]
I assume you meant to link to https://github.com/mstange/samply/blob/1d71084e3054a9d2b6bd9a399cfcd659f937f613/samply/src/linux_shared/kernel_symbols.rs.

Is adding a public API to construct it enough to close this issue?

**Comment by mstange** [comment]
Hah, yes, you found the right link. Yes, adding a public API for `NoteIterator` would be enough to close this issue.

And maybe a doc comment which says whether to pass 4 or 8 to the `align` argument when using it with `/sys/kernel/notes` - I didn't actually check how that works.
