### ISSUE TITLE
Microsoft has a COFF file format that they use to describe imports

### ISSUE THREAD

**Issue by invlpg** [gimli-rs/object#512]
https://docs.rs/object/latest/object/read/archive/enum.ArchiveKind.html

There exists an "import coff" file format which is essentially just an import descriptor table entry that the linker uses. 

You can read more about it here:

https://learn.microsoft.com/en-us/windows/win32/debug/pe-format#import-library-format

**Comment by invlpg** [comment]
For example if you try and parse a import coff `object` is going to explode on this line:

https://docs.rs/object/latest/src/object/read/archive.rs.html#320

**Comment by philipc** [comment]
Are you sure it fails on that line? I would expect the archive parsing to not care about the format of the archive members.

**Comment by invlpg** [comment]
the archive parser itself doesnt care, but CoffFile isnt happy. Maybe Ill make a pull request with msvc import object support soon

**Comment by philipc** [comment]
`CoffFile` will never be happy with it because it's not an object file. It will need a separate simple parser specifically for the short import library format (header + 2 strings), and perhaps file format detection in `FileKind`.

**Comment by philipc** [comment]
Implemented in #555

**Comment by CR3Swapper** [comment]
thanks brother man 🙏
