### ISSUE TITLE
Very long loop while parsing in `MachOFile::parse`

### ISSUE THREAD

**Issue by Arthur-PI** [gimli-rs/object#515]
Hello, while fuzzing I found a binary file (probably ill-formed) that takes around 10 minutes to be parsed on my machine. But the file is only 396 bytes. This might not be a bug and just an expected outcome of the binary lying about its data, but it would be nice if this can be avoided.  
What I've discovered if this can help is that this while loop in `MachOFile::parse` is looping all the time over `commands.next()`
https://github.com/gimli-rs/object/blob/a3706b514992d8292b799ae67652096aa0085ca3/src/read/macho/file.rs#L58-L69
And the `next` implementation of `LoadCommandIterator` is decrementing its inner variable `ncmds` by 1 each iteration and returning None when it's 0. But the thing is the initial value of `ncmds` is `3 992 977 412` 😮  

Here is the file to reproduce: [test.zip](https://github.com/gimli-rs/object/files/10757936/test.zip)

**Comment by philipc** [comment]
Thanks very much for the report. That test file also uncovered a couple more bugs, all fixed in #516.
