### ISSUE TITLE
Depends on an outdated and soon-to-be-defunct version of wasmparser

### ISSUE THREAD

**Issue by kornelski** [gimli-rs/object#523]
Compilation of gimli examples warns:

> warning: the following packages contain code that will be rejected by a future version of Rust: wasmparser v0.57.0
> …
> warning: trailing semicolon in macro used in expression position
> https://github.com/rust-lang/rust/issues/79813

This error is in a very very old version of wasmparser, so presumably it has been fixed already, but `object` still has a dev-dependency on the bad old version.

**Comment by philipc** [comment]
wasm support in this crate hasn't been maintained for a long time. @RReverser Are you still using the wasm support?

**Comment by RReverser** [comment]
Not in the current project, but I do from time to time. In theory, Wasm support shouldn't require active maintenance, since it's just used as a container for DWARF sections, but bumping the dependency is worthwhile, yeah.

**Comment by philipc** [comment]
@RReverser Updating `wasmparser` is a large task which I personally do not wish to undertake. What exactly do you need from the wasm support in this crate? Can we go back to a simple parser which is sufficient to provide access to the DWARF sections (which is all I need it for)?

**Comment by philipc** [comment]
It ended up not being too bad to update wasmparser, see #528.

**Comment by RReverser** [comment]
> Can we go back to a simple parser which is sufficient to provide access to the DWARF sections (which is all I need it for)?

Hm I don't really remember enough context, it's been years - what do you mean by "go back" or "simple parser"?

> It ended up not being too bad to update wasmparser, see #528.

Looks great!
