### ISSUE TITLE
Add support for conditionally building support for each object format

### ISSUE THREAD

**Issue by jrmuizel** [gimli-rs/object#53]
Goblin has a set of features that let you choose which formats are supported. It would be nice if we could have the same for 'object'. This can cut down on code size in situations where you only need to support the native format of the platform you're running on. An example use case for this is backtrace-rs, additionally we'd like this for use in the profiler in Gecko.

**Comment by philipc** [comment]
My intent was that you would use `ElfFile` etc in this case, since they all implement the object trait. What if we added a `NativeFile` type alias that depended on the target OS? That way users don't need to fiddle with feature flags.

**Comment by jrmuizel** [comment]
The problem with that approach is that addr2line wants an actual 'File':
https://docs.rs/addr2line/0.6.0/addr2line/struct.Context.html#method.new

**Comment by philipc** [comment]
It only needs the `File` to read sections though, so that's easily changed.

**Comment by jrmuizel** [comment]
In that case adding a NativeFile type alias seems like a fine solution.
