### ISSUE TITLE
Please release a new version on crates.io

### ISSUE THREAD

**Issue by mstange** [gimli-rs/object#55]
I'd like to make use of the `debug_file_info()` method that was added in #39, but that method was not included in the 0.7.0 release and there hasn't been a new release since then.

**Comment by philipc** [comment]
I think we can release a new version once #54 is merged. Note that addr2line will need updating for the `Cow` changes before it can use the new version, in case you're using it too.

**Comment by mstange** [comment]
I'm no longer in a rush to use `debug_file_info()` because I've found https://github.com/getsentry/symbolic/tree/master/debuginfo which is actually a better match for my use case - it has `get_mach_id()` and `get_elf_id()` functions.

**Comment by philipc** [comment]
So the bit this crate is missing is the ELF id?

**Comment by mstange** [comment]
Yes... but I'd still need some of the other functionality in the debuginfo crate.

What I really need is to compute the "debug ID" that the Breakpad symbol processor would have computed for the file, in order to check whether I have the right file. And that computation doesn't just take the ELF build id, it also munges it a little (ignores everything after the first 16 bytes + converts it to big endian), and it has a fallback implementation for object files that don't contain a build id note. The debuginfo crate aims to match Breakpad's behavior.

This munging + fallback computation doesn't seem like something that should be in the object crate.

**Comment by philipc** [comment]
0.8.0 is released.

I agree that the breakpad stuff probably doesn't belong here.
