### ISSUE TITLE
Support writing from an `Object::read::File`

### ISSUE THREAD

**Issue by hwittenborn** [gimli-rs/object#559]
I have an existing ELF file that I'd like to change the loader in (similar to the [`patchelf`](https://github.com/NixOS/patchelf) tool), but it doesn't look like there's any easy way to do that with this library.

Is there something technical that's stopping `Object::read::File` from being able to write files back out?

**Comment by bjorn3** [comment]
If you want to patch an executable you will have to use the low level writing interface. The high level one is only capable of producing object files. You could take a look at the elfcopy example: https://github.com/gimli-rs/object/blob/b237c5c603bda4fc77eec4db951d833b79cb543d/crates/examples/src/bin/elfcopy.rs

**Comment by hwittenborn** [comment]
Alright, I'll give that all a look. Thanks for the help!

**Comment by philipc** [comment]
The technical reason is that `object::read::File ` tries not to make copies of anything, so you wouldn't be able to modify anything before writing back out, and there's no point writing without modifications.

Currently you need to do what either the `objcopy` or `elfcopy` examples do, but there's scope for adding something to the crate to make those easier.

**Comment by hwittenborn** [comment]
I'm fine with the ways you linked you @philipc - I'm still looking into the use case I'm working on with my program, and I'm not positive I'll need to work with ELF files now anyway. If I do need to those examples should be more than fine, I'm always down for making everything more user-friendly though :)
