### ISSUE TITLE
how can i get LoadConfig and ImageCore20Header tables for pe ?

### ISSUE THREAD

**Issue by NofAssiri** [gimli-rs/object#566]
i couldn`t find the api to get them, do i have to map them manually ? thanks in advance  ?

**Comment by philipc** [comment]
Currently there's no API for these, only the structure definitions. Here's some old unfinished code I wrote that may help: https://github.com/gimli-rs/object/commit/be996294de9035954ec01a27f0757e05b44b9179

**Comment by NofAssiri** [comment]
> Currently there's no API for these, only the structure definitions. Here's some old unfinished code I wrote that may help: [be99629](https://github.com/gimli-rs/object/commit/be996294de9035954ec01a27f0757e05b44b9179)

i mapped them using this way but i was looking for more efficient way. thank you.
