### ISSUE TITLE
read/coff: Support m68k COFF object files

### ISSUE THREAD

**Issue by pjlafren** [gimli-rs/object#567]
This is the only rust library that I can find that has any sort of interface with COFF object files*.  But once I tried to use it, I found that it had no support for my target architecture.

After spending time adding constants and updating relocation code, I discovered that the COFF & PE modules are inextricably tied to little endian headers, and does not appear to be easy to allow for varied endianness without a significant rewrite.

That is, unless my limited Rust skills are hiding a simpler approach. 

*Even GNU BFD dropped support for m68k-coff in 2018.

**Comment by philipc** [comment]
The definitions in `src/pe.rs` are specifically for Windows COFF, which is always little endian, and anything that uses them is likewise specifically for Window COFF.

Can you provide a link to any documentation for m68k COFF? Which open source projects do have support for this format? Also what sort of task would you be using this for?

**Comment by asdf2jkl** [comment]
GNU binutils used to have support for m68k COFF up until 2018 when it and m68k a.out were removed from bfd. I personally use tigcc/gcc4ti all the time, which builds upon the binutils support for the format.

At the moment I am working on trying to create matching decompiltions of code built using the Sierra C compiler, which only emits object code in COFF format. If I can parse the my output object files then I can extract individual functions for comparison with the source binary.

**Comment by philipc** [comment]
Can you provides links to somewhere that shows the file format definitions?

**Comment by asdf2jkl** [comment]
Here are the best (albeit not amazing) resources that I know of offhand:

- GNU Binutils coff-m68k.c and include/coff/m68k.h:
https://sourceware.org/git/?p=binutils-gdb.git;a=blob;f=bfd/coff-m68k.c;h=c1be3eea9ae560addefa170f83a470f66b9a8383;hb=a783ed1a1ba08d73583da5a56470e4af5acfb6bd
and
https://sourceware.org/git/?p=binutils-gdb.git;a=blob;f=include/coff/m68k.h;h=5c5f758f50dbf3086052868664a755bf3408ad1c;hb=a783ed1a1ba08d73583da5a56470e4af5acfb6bd
- The TIGCC linker: https://github.com/debrouxl/gcc4ti/blob/next/trunk/tigcc/ld-tigcc/formats/coff.h
- The TI FLASH Studio/Sierra C compiler guide: https://web.archive.org/web/20130712132305/http://isa.umh.es/calc/TI/TI89-92SDK/sdk8992pcompiler.pdf

**Comment by philipc** [comment]
Given that neither LLVM nor binutils currently have support, and your use case doesn't appear to benefit from sharing code with other file formats, I'm reluctant to add support to this crate. Based on the definitions in the TIGCC linker, it shouldn't be much effort to write a simple parser for what you need.

**Comment by asdf2jkl** [comment]
That's entirely fair. As I said before, I had tried to add support myself but found that the entire COFF/PE parsing code would need an overhaul for it. I doubt that anyone other than myself would use m68k COFF, and the only code sharing potential is with a PowerPC COFF that would get even less use.

I'll just make my own specialized parser. Shouldn't be too bad, though given the fact that the TIGCC linker is the second least readable code I've ever come across, it might get complicated to handle the format properly.
