### ISSUE TITLE
How can I write an ELF64 executable?

### ISSUE THREAD

**Issue by InfiniteCoder01** [gimli-rs/object#577]
I'm just starting my journey with ELF's, how can I write an ELF64 executable with this crate?
I couldn't find any examples, nor functions in API. Readme says:
`and writing COFF/ELF/Mach-O/XCOFF relocatable object files and ELF/PE executable files.`

**Comment by bjorn3** [comment]
You have to use the [low level ELF writer api](https://docs.rs/object/0.32.1/object/write/elf/struct.Writer.html) for that. It is not the easiest to use though and barely abstracts over ELF. You are responsible for specifying the final memory location of everything as well as reserve space for all the ELF data structures before writing them. You also have to apply relocations and such yourself. Effectively you have to take most of the functionality of a linker upon you. Writing relocatable object files using the [unified writer api](https://docs.rs/object/0.32.1/object/write/struct.Object.html) and then invoking an external linker is likely a much better choice, especially when you are not very familiar with how ELF works.

**Comment by philipc** [comment]
@InfiniteCoder01 I see you wrote your own crate, so closing this issue. Feedback about why this crate wasn't suitable would still be welcome.

**Comment by InfiniteCoder01** [comment]
Since I had to use low level ELF api, I've decided to write my own crate. This wouldn't be much harder (or so I thought) and it will do only what I need,
