### ISSUE TITLE
Expose p_type and p_flags from API

### ISSUE THREAD

**Issue by pcc** [gimli-rs/object#600]
In my program I need to read all executable ELF segments, starting from an `ElfFile`. I tried this:
```
for s in elf.segments() {
    if s.segment.p_type(elf.endian()) != elf::PT_LOAD || s.segment.p_flags(elf.endian()) & elf::PF_X == 0 {
        continue
    }
    /* ... */
}
```
but this didn't work because `segment` wasn't public. I'm working around it for now with a local hack to the package that makes `segment` public. Am I missing something or is it not possible to get to the `ProgramHeader` or otherwise access this information via the public API?

**Comment by philipc** [comment]
`elf.segments()` is already only the segments that are `PT_LOAD`, so you don't need to check that. You can use `segment.flags()` to examine the ELF program header flags.

Other options are to use `elf.raw_segments()` instead of `elf.segments()`, or use `read::elf::FileHeader` instead of `ElfFile`.

**Comment by pcc** [comment]
Thanks!
