### ISSUE TITLE
Subtraction with overflow in example

### ISSUE THREAD

**Issue by matthiasbeyer** [gimli-rs/object#611]
https://github.com/gimli-rs/object/blob/c87a9bda506a63fc882f95b40db8e929680f9ee1/crates/examples/src/objcopy.rs#L69

The above line overflows for me.

**Comment by philipc** [comment]
Can you provide a file that this happens for?

**Comment by matthiasbeyer** [comment]
I tried it on the `patchelf` binary.

**Comment by philipc** [comment]
That sounds like an executable file, not a relocatable object file, so not a surprise it failed. The `objcopy` example only works for files that `write::Object` can write. We should have prevented it from getting that far with this check though: https://github.com/gimli-rs/object/blob/c87a9bda506a63fc882f95b40db8e929680f9ee1/crates/examples/src/objcopy.rs#L17

The `elfcopy` example might have a better chance of working.

**Comment by matthiasbeyer** [comment]
Ah, thanks a lot for pointing me! I indeed removed the line you quoted, that's why it didn't catch my error.
Thanks!
