### ISSUE TITLE
Update goblin dependency to 0.0.17

### ISSUE THREAD

**Issue by ignatenkobrain** [gimli-rs/object#62]
That would be helpful for me in order to update goblin to latest version.

**Comment by fitzgen** [comment]
We started using dependabot in the rustwasm org and it has made staying on
top of the latest versions of dependencies a lot easier. It automatically
makes PRs to update dependencies and you can configure it  to merge if ci
passes too.

We should probably set it up for gimli repos, and then you won't have to do
the job manually anymore, Igor :-p

What do you think @philipc?

**Comment by ignatenkobrain** [comment]
@fitzgen Unfortunately it can't automatically port code ;)

**Comment by philipc** [comment]
@fitzgen I'd be fine if you want to set that up. It lets us know when there are dependencies that need updating at least. I'd prefer if it didn't automatically merge though.

**Comment by philipc** [comment]
@ignatenkobrain Do you want a new object release too? (and gimli/addr2line?).

**Comment by ignatenkobrain** [comment]
up to you guys, for now I just carry this patch along with a package :)

Reducing number of downstream patches is good. So if you have some time, do so please ;)

**Comment by fitzgen** [comment]
Added dependabot, but configured not to merge PRs by default.
