### ISSUE TITLE
Add asynchronous ReadCache

### ISSUE THREAD

**Issue by russellbanks** [gimli-rs/object#624]
I want to avoid reading an entire file in memory. However, it's very difficult to use this library in an asynchronous context with ReadCache:

1. ReadCache uses RefCell internally which is not thread-safe
2. ReadCache requires the synchronous Read and Seek

I know it's a big ask but a tokio feature that implements AsyncRead and AsyncWrite, perhaps using an alternative like RwLock instead of RefCell, would help to use this library in an asynchronous context.

**Comment by philipc** [comment]
The library was initially written with the intent of using something like mmap. Is mmap unavailable or unsuitable in your environment?

Is there anything preventing you from writing your own implementation of `ReadRef` that handles async?

**Comment by russellbanks** [comment]
Thanks @philipc. I'd never used mmap before and this fits my case perfectly. Before this, I'd written a custom implementation of `ReadCache` that swapped out RefCell for RwLock. That at least meant that it had Send + Sync.
