### ISSUE TITLE
can this crate be used to write a cross platform linker

### ISSUE THREAD

**Issue by ctrlv0** [gimli-rs/object#634]

**Comment by philipc** [comment]
The unified read API provided by this crate is not suitable for writing a cross platform linker. It loses some of the details in translation, and that is not desirable for a linker.

The low level read APIs for each format should be usable, but may need fleshing out more, and maybe aren't what you are looking to use for a "cross platform" linker.

The `write::Object` API is only for writing object files, not for the result of a linker. `write::elf::Writer` and `write::pe::Writer` should work (and the yet to be written `write::macho::Writer`), but again may not be what you are looking to use for a "cross platform" linker.

Short answer: yes, but not all of the APIs provided by this crate are suitable, and you probably need to build your own cross platform abstractions on top of it.

**Comment by ctrlv0** [comment]
hmm any other crate which does the same?

**Comment by philipc** [comment]
The only other parser I know of that supports multiple file formats is goblin. You'll have to evaluate whether its API meets your needs, since you haven't given any detail about your desired design for a "cross platform" linker.

**Comment by ctrlv0** [comment]
> The only other parser I know of that supports multiple file formats is goblin. You'll have to evaluate whether its API meets your needs, since you haven't given any detail about your desired design for a "cross platform" linker.

kind like lld, I want my own case specif8c linker for a programming language I'm developing

**Comment by philipc** [comment]
If you look at the lld source, there's a lot of code in each format specific directory, and not much in the common directory. It's similar if you look at Zig's linker. They don't use anything like the unified API this crate provides. The format specific APIs in this crate should be suitable for implementing something like that. With that kind of design, there's little benefit to making it cross platform up front. Write your linker for one platform, and worry about making it cross platform later. Also, try to avoid writing your own linker if at all possible.
