### ISSUE TITLE
`NOBITS` with `sh_offset==0` causes `build::elf::Builder::write` error

### ISSUE THREAD

**Issue by allvpv** [gimli-rs/object#644]
Hello. AFAIK `sh_offset` field is completely meaningless in case of `SHT_NOBITS` section. Sometimes it is equal to `0`: I encountered such a binary "in the wild". In this case, however, you cannot `write` the (valid) binary parsed by the ELF builder: it throws an error. 

Probably the simplest  possible solution would be to add another conditional (`section.sh_type != SHT_NOBITS`) around this fragments of code from `build/elf.rs`:

```rust
if section.sh_offset < writer.reserved_len() as u64 { ... }
```

```rust
// The input sh_offset needs to be preserved so that offsets in program
// headers are correct.
writer.reserve_until(section.sh_offset as usize);
```

```rust
if out_section.offset as u64 != section.sh_offset {...}
```

Let me know what do you think.

**Comment by philipc** [comment]
Thanks for the report. #645 fixes this similar to how you suggest.

Running on a few more binaries in the wild shows that there's likely other things that need fixing too.
