### ISSUE TITLE
Support reading thin archives

### ISSUE THREAD

**Issue by bjorn3** [gimli-rs/object#648]
This is necessary to fix https://github.com/rust-lang/rust/issues/107407 and allow moving rustc from LLVM's archive writer to ar_archive_writer again. The api for this should probably not directly read the member contents from the disk, but only parse the thin archive to get the member names (and optionally read the symbol table) to allow the consumer of this api to read them from the disk as necessary.

**Comment by philipc** [comment]
#651 has thin archive support. What do you need for symbol table support? The symbol table contains a list of member offsets and symbol names. I can provide an iterator that returns those, and an `Archive` method to return a member at a given offset. Is that sufficient?

**Comment by bjorn3** [comment]
The symbol table of the original archives is not currently used by the archive writer in rustc. It unconditionally looks directly at the object files. So at least for now reading the symbol table is not necessary.

**Comment by philipc** [comment]
I'll leave symbol table support for #479
