### ISSUE TITLE
Relocation source

### ISSUE THREAD

**Issue by Toni-Graphics** [gimli-rs/object#668]
How can I get the source symbol index/name of a Relocation?

Something like `Relocation.target()` but as `Relocation.source()`

Bye

**Comment by philipc** [comment]
This crate doesn't give you the source symbol. It only gives you what is stored in the object file, which is the section offset (for relocatable object files) or address (for dynamic relocations). If it is an address, you could pass that to a [`SymbolMap`](https://docs.rs/object/0.35.0/object/read/trait.Object.html#method.symbol_map), but we don't provide anything to convert a section offset to a symbol.

Why do you want to do this? Generally this is not useful information. The section offset or address is sufficient to handle the relocation.

**Comment by Toni-Graphics** [comment]
I am currently building a dissasembler and i need it for filtiering out which relocation is for which symbol so i can get the relocs for the current function to disassemble

**Comment by philipc** [comment]
The first field of the [`Item` tuple returned by the section relocator iterator](https://docs.rs/object/latest/object/read/trait.ObjectSection.html#associatedtype.RelocationIterator) is the address or offset, so you can check if that is within the function you are disassembling.

**Comment by Toni-Graphics** [comment]
Thx, i now hav it.
I have one other question:
How can i get the position of the reloc relativ to the function?

**Comment by philipc** [comment]
I don't know what you mean. There is no function named `pos` in `object`. [`RelocationKind`](https://docs.rs/object/latest/object/read/enum.RelocationKind.html#variant.Relative) documents the expression for its variants.

**Comment by Toni-Graphics** [comment]
> There is no function named `pos` in `object`. 

It is a virtual function which i used, which should make it easyer to show what I meant.

> I don't know what you mean

I am searching a function which gets the relative position of the relocation to a symbol/section.
Let's say we have a section main with the data: [0x12, 0x34, 0x56, 0x78, 0x90]
To the 2nd byte (0x34) is a relocation.

I want to find out when i then read the file/relocation that it (the relocation) is pointing to the 2nd byte in that symbol/section

**Comment by Toni-Graphics** [comment]
Maybe the [`RelocationMap`](https://docs.rs/object/latest/object/read/struct.RelocationMap.html) struct is useful?

**Comment by philipc** [comment]
`RelocationMap` is only for DWARF relocations.

I still don't know what you mean. Let's try a real example.

```
$ cargo run --bin simple_write --features write
$ objdump -dr hello.o 

hello.o:     file format elf64-x86-64


Disassembly of section .text.main:

0000000000000000 <main>:
   0:	48 83 ec 28          	sub    $0x28,%rsp
   4:	48 8d 3d 00 00 00 00 	lea    0x0(%rip),%rdi        # b <main+0xb>
			7: R_X86_64_PC32	.rodata-0x4
   b:	e8 00 00 00 00       	call   10 <main+0x10>
			c: R_X86_64_PLT32	puts-0x4
  10:	31 c0                	xor    %eax,%eax
  12:	48 83 c4 28          	add    $0x28,%rsp
  16:	c3                   	ret    
```

Here I've used `objdump` to disassemble and show relocations for the object file produced by the `simple_write` example. I think you're trying to write code to do this. In particular, you want to know how to display a relocation such as this:
```
   b:	e8 00 00 00 00       	call   10 <main+0x10>
			c: R_X86_64_PLT32	puts-0x4
```

You need to look at the sections, symbols, and relocations in the file. Here's the relevant ones:
```
$ target/debug/objdump hello.o 
1: Section { name: ".text.main", address: 0, size: 17, align: 1, kind: Text, flags: Elf { sh_flags: 6 } }

3: Symbol { name: "main", address: 0, size: 17, kind: Text, section: Section(SectionIndex(1)), scope: Linkage, weak: false, flags: Elf { st_info: 12, st_other: 2 } }
4: Symbol { name: "puts", address: 0, size: 0, kind: Unknown, section: Undefined, scope: Unknown, weak: false, flags: Elf { st_info: 10, st_other: 0 } }
```

The symbol with index 3 is the `main` symbol. It is located in the section with index 1, which is `.text.main`. Its address is 0, so it is located at the start of the section, and its size is 0x17 bytes. So the `main` symbol occupies bytes 0x0-0x16 within the `.text.main` section.

```
$ target/debug/objdump hello.o
.text.main relocations
(c, Relocation { kind: PltRelative, encoding: Generic, size: 20, target: Symbol(SymbolIndex(4)), addend: fffffffffffffffc, implicit_addend: false, flags: Elf { r_type: 4 } })
```

This is a relocation for a place in the `.text.main` section at offset 0xc with a size of 4 bytes (0x20 bits). So the place of this relocation occupies bytes 0xc-0xf within the `.text.main` section. The target of the relocation is the symbol with index 4, which is `puts`, and the addend is -4 (0xfffffffffffffffc).

Comparing the byte range 0x0-0x16 with the byte range 0xc-0xf, we see that the relocation is within the `main` function.

Given that context, what is your question?

**Comment by Toni-Graphics** [comment]
Yes,
Would be `relocation.adress() - symbol.adress()` the relocation offset from the symbol?

**Comment by philipc** [comment]
Sure, that's how addresses work.
