### ISSUE TITLE
Add PE to the unified api

### ISSUE THREAD

**Issue by Toni-Graphics** [gimli-rs/object#671]
Maybe you can add that you can use the file format pe in the unified api like coff.

Bye

**Comment by bjorn3** [comment]
The unified api is for writing relocatable object files, not executables and dynamic libraries. AFAIK PE only exists for executables and dynamic libraries. PE is COFF + a stub executable by MSDOS, which relocatable object files don't need as they will never be executed.

**Comment by Toni-Graphics** [comment]
Ok
