### ISSUE TITLE
How to check if elf is statically linked?

### ISSUE THREAD

**Issue by NobodyXu** [gimli-rs/object#682]
I want to check if an elf object is statically linked.

I've found [`Object::kind`](https://docs.rs/object/latest/object/read/trait.Object.html#tymethod.kind), however I'm not sure which variants in [`ObjectKind`](https://docs.rs/object/latest/object/read/enum.ObjectKind.html) refers to a statically linked.

**Comment by philipc** [comment]
There's nothing in the unified API, and even `ObjectKind` [isn't completely accurate](https://github.com/gimli-rs/object/blob/0643b61e1db0eb97e320c3ca80d07a9e82897a9a/src/read/elf/file.rs#L249).


For now, you'll need to use the lower level ELF APIs to read the ELF header flags and the program headers (e.g. check for `PT_INTERP` and/or `PT_DYNAMIC`, I don't know what the exact check is).

**Comment by NobodyXu** [comment]
Thanks for the quick reply!

I found that goblin supports getting program header https://docs.rs/goblin/latest/goblin/elf/struct.Elf.html and have [PT_INTERP](https://docs.rs/goblin/latest/goblin/elf/program_header/constant.PT_INTERP.html) defined in the crate

**Comment by philipc** [comment]
goblin is certainly the easiest way to do it, but if all you want is to check if it is statically linked then it's doing a lot of parsing that you don't need. I don't know if that matters.

**Comment by NobodyXu** [comment]
For cargo-binstall, most of the time is spent on network and the elf shouldn't be too big, so I think it should be ok
