### ISSUE TITLE
Elf: Error while processing .so file

### ISSUE THREAD

**Issue by mcbegamerxx954** [gimli-rs/object#704]
Hi, im using the object-rewrite crate in a tool that patches a needed library into aarch64 libminecraft.so the library of the minecraft app for android, but while processing the file it gets this error: `
Unaligned sh_offset value 0x228be4 for section '.gnu.version_r', expected 0x228be8`
is there any fix?, the library loads fine on my device after testing, armv7a patching works fine for some reason

**Comment by mcbegamerxx954** [comment]
> Hi, im using the crate in this repo called object-rewrite in a tool that patches a needed library into aarch64 libminecraft.so the library of the minecraft app for android, but while processing the file it gets this error: `
> Unaligned sh_offset value 0x228be4 for section '.gnu.version_r', expected 0x228be8`
> is there any fix?, the library loads fine on my device after testing, armv7a patching works fine for some reason

**Comment by philipc** [comment]
I need to be able to reproduce the problem to be able to fix it. Where can I download the .so?

**Comment by mcbegamerxx954** [comment]
> I need to be able to reproduce the problem to be able to fix it. Where can I download the .so?

I dont really know how i can go about this since its a paid android game, but im open for testing with my copy

**Comment by philipc** [comment]
I've previously seen a similar error on another .so: `Unsupported sh_offset value 0xb878 for section '.gnu.version_r', expected at least 0xb880`. I guess it's possible that it is the same cause, so I'll try fixing that and see if it helps.

**Comment by philipc** [comment]
Can you test if #705 fixes it for you?

**Comment by philipc** [comment]
In the likely event that doesn't help, can you give me the output of running:
`target/debug/readobj --file-header --segments --sections libminecraft.so`

**Comment by mcbegamerxx954** [comment]
That did not work, but here is the readelf output
![result.txt](https://github.com/user-attachments/files/16287237/result.txt)

**Comment by philipc** [comment]
I think #706 will fix this.

**Comment by mcbegamerxx954** [comment]
That seems to fix it, thanks!

**Comment by mcbegamerxx954** [comment]
Oops, forgot to wait for merge
