### ISSUE TITLE
Support ELF .relr relocations

### ISSUE THREAD

**Issue by bjorn3** [gimli-rs/object#722]
https://maskray.me/blog/2021-10-31-relative-relocations-and-relr has an explanation of the format.

**Comment by philipc** [comment]
Is there anything in particular you want to be able to use this to do?

**Comment by bjorn3** [comment]
At the very least I would like reader support for `.relr` relocations. Arch Linux started using them 6 months ago: https://gitlab.archlinux.org/archlinux/packaging/packages/pacman/-/merge_requests/6 As did Fedora: https://src.fedoraproject.org/rpms/redhat-rpm-config/c/5fca01a Without `.relr` support in object, this would mean every user of object that wants to read all relocations in executables would miss a ton of relocations in executables compiled by Fedora and Arch.
