### ISSUE TITLE
Add archive support

### ISSUE THREAD

**Issue by philipc** [gimli-rs/object#82]
Add an iterator over objects in an archive. It would be nice if this same iterator also worked for Mach-O fat binaries, and also returned a single object for files that aren't archives.

**Comment by philipc** [comment]
goblin already has some support for this too, and using it would avoid another dependency.

**Comment by bjorn3** [comment]
Didn't know that.

**Comment by philipc** [comment]
Fixed in #252. I decided it wasn't useful to try to share anything with Mach-O fat binaries.

**Comment by messense** [comment]
#252 added archive read support, does `object` support write archive?

**Comment by bjorn3** [comment]
Not at the moment.
